import {
  Ad,
  Add,
  AddressBook,
  AddressCard,
  Adjust,
  AirFreshener,
  Aletter,
  AlignCenter2,
  AlignJustify2,
  AlignLeft2,
  AlignRight2,
  Allergies,
  Ambulance,
  AmericanSignLanguageInterpreting,
  Anchor2,
  AnchorCircleCheck,
  AnchorCircleExclamation,
  AnchorCircleXmark,
  AnchorLock,
  AngleDoubleDown,
  AngleDoubleLeft,
  AngleDoubleRight,
  AngleDoubleUp,
  AngleDown,
  AngleLeft,
  AngleRight,
  AnglesDown,
  AnglesLeft,
  AnglesRight,
  AnglesUp,
  AngleUp,
  Angry,
  Ankh,
  AppleWhole,
  Archive2,
  Archway,
  AreaChart,
  ArrowAltCircleDown,
  ArrowAltCircleLeft,
  ArrowAltCircleRight,
  ArrowAltCircleUp,
  ArrowRightArrowLeft,
  ArrowRightFromBracket,
  ArrowRightFromFile,
  ArrowRightLong,
  ArrowRightRotate,
  ArrowRightToBracket,
  ArrowRightToCity,
  ArrowRightToFile,
  ArrowRotateBack,
  ArrowRotateBackward,
  ArrowRotateForward,
  ArrowRotateLeft,
  ArrowRotateRight,
  Arrows,
  ArrowsAlt,
  ArrowsAltH,
  ArrowsAltV,
  ArrowsDownToLine,
  ArrowsDownToPeople,
  ArrowsLeftRight,
  ArrowsRotate,
  ArrowsUpDown,
  ArrowTrendDown,
  ArrowTrendUp,
  ArrowTurnDown,
  ArrowTurnUp,
  ArrowUp19,
  ArrowUp91,
  ArrowUpAZ,
  ArrowUpFromBracket,
  ArrowUpFromGroundWater,
  ArrowUpFromWaterPump,
  ArrowUpLong,
  ArrowUpRightDots,
  ArrowUpRightFromSquare,
  ArrowUpShortWide,
  ArrowUpWideShort,
  ArrowUpZA,
  AslInterpreting,
  AssistiveListeningSystems,
  Asterisk,
  At,
  Atlas,
  Atom,
  AudioDescription,
  AustralSign,
  Automobile,
  Award2,
  Baby,
  BabyCarriage,
  Backspace,
  Backward,
  BackwardFast,
  BackwardStep,
  Bacon,
  Bacteria,
  Bacterium,
  BagShopping,
  Bahai,
  BahtSign,
  BalanceScale,
  BalanceScaleLeft,
  BalanceScaleRight,
  Ban,
  BandAid,
  BanSmoking,
  Bletter,
  Bookmark,
  BookMedical,
  BookOpen,
  BookOpenReader,
  BookQuran,
  BookReader,
  BookSkull,
  BookTanakh,
  BorderAll,
  BorderNone,
  BorderStyle,
  BorderTopLeft,
  BoreHole,
  BottleDroplet,
  BottleWater,
  BowlFood,
  BowlingBall,
  BowlRice,
  Box,
  BoxArchive,
  Boxes,
  BoxesPacking,
  BoxesStacked,
  BoxOpen,
  BoxTissue,
  Braille,
  Brain,
  BrazilianRealSign,
  BreadSlice,
  Bridge,
  BridgeCircleCheck,
  BridgeCircleExclamation,
  BridgeCircleXmark,
  BridgeLock,
  BridgeWater,
  Briefcase,
  BriefcaseClock,
  BriefcaseMedical,
  BroadcastTower,
  Broom,
  BroomBall,
  Brush,
  Bucket,
  Bug,
  Bugs,
  BugSlash,
  Building,
  BuildingCircleArrowRight,
  BuildingCircleCheck,
  BuildingCircleExclamation,
  BuildingCircleXmark,
  BuildingColumns,
  BuildingFlag,
  BuildingLock,
  BuildingNgo,
  BuildingShield,
  BuildingUn,
  BuildingUser,
  BuildingWheat,
  Bullhorn,
  Bullseye,
  Burger,
  Burn,
  Burst,
  Bus,
  BusAlt,
  BusinessTime,
  BusSimple,
  Cab,
  CableCar,
  Cake,
  CakeCandles,
  Calculator,
  Calendar,
  CalendarAlt,
  CalendarCheck,
  CalendarDay,
  CalendarDays,
  CalendarMinus,
  CalendarPlus,
  CalendarTimes,
  CalendarWeek,
  CalendarXmark,
  Camera,
  CameraAlt,
  CameraRetro,
  CameraRotate,
  Campground,
  Cancel,
  CandyCane,
  Cannabis,
  Capsules,
  Car,
  CarAlt,
  Caravan,
  CarBattery,
  CarBurst,
  CarCrash,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretSquareDown,
  CaretSquareLeft,
  CaretSquareRight,
  CaretSquareUp,
  CaretUp,
  CarOn,
  CarRear,
  CarriageBaby,
  Carrot,
  CarSide,
  CartArrowDown,
  CartFlatbed,
  CartFlatbedSuitcase,
  CartPlus,
  CartShopping,
  CarTunnel,
  CashRegister,
  Cat,
  CediSign,
  CentSign,
  Certificate,
  Chain,
  ChainBroken,
  ChainSlash,
  Chair,
  Chalkboard,
  ChalkboardTeacher,
  ChalkboardUser,
  ChampagneGlasses,
  ChargingStation,
  ChartArea,
  ChartBar,
  ChartColumn,
  ChartDiagram,
  ChartGantt,
  ChartLine,
  ChartPie,
  ChartSimple,
  Check,
  CheckCircle,
  CheckDouble,
  CheckSquare,
  CheckToSlot,
  Cheese,
  Chess,
  ChessBishop,
  ChessBoard,
  ChessKing,
  ChessKnight,
  ChessPawn,
  ChessQueen,
  ChessRook,
  ChevronCircleDown,
  ChevronCircleLeft,
  ChevronCircleRight,
  ChevronCircleUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Child,
  ChildCombatant,
  ChildDress,
  ChildReaching,
  Children,
  ChildRifle,
  Church,
  Circle,
  CircleArrowDown,
  CircleArrowLeft,
  CircleArrowRight,
  CircleArrowUp,
  CircleCheck,
  CircleChevronDown,
  CircleChevronLeft,
  CircleChevronRight,
  CircleChevronUp,
  CircleDollarToSlot,
  CircleDot,
  CircleDown,
  CircleExclamation,
  CircleH,
  CircleHalfStroke,
  CircleInfo,
  CircleLeft,
  CircleMinus,
  CircleNodes,
  CircleNotch,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleQuestion,
  CircleRadiation,
  CircleRight,
  CircleStop,
  CircleUp,
  CircleUser,
  CircleXmark,
  City,
  Clapperboard,
  Cletter,
  ClinicMedical,
  Clipboard2,
  ClipboardCheck,
  ClipboardList,
  ClipboardQuestion,
  ClipboardUser,
  Clock,
  ClockFour,
  ClockRotateLeft,
  Clone,
  Close,
  ClosedCaptioning,
  Cloud,
  CloudArrowDown,
  CloudArrowUp,
  CloudBolt,
  CloudDownload,
  CloudDownloadAlt,
  CloudMeatball,
  CloudMoon,
  CloudMoonRain,
  CloudRain,
  CloudShowersHeavy,
  CloudShowersWater,
  CloudSun,
  CloudSunRain,
  CloudUpload,
  CloudUploadAlt,
  Clover,
  Cny,
  Cocktail,
  Code,
  CodeBranch,
  CodeCommit,
  CodeCompare,
  CodeFork,
  CodeMerge,
  CodePullRequest,
  Coffee2,
  Cog,
  Cogs,
  Coins,
  ColonSign,
  Columns,
  Comment2,
  CommentAlt,
  CommentDollar,
  CommentDots,
  Commenting,
  CommentMedical,
  CommentNodes,
  Comments,
  CommentsDollar,
  CommentSlash,
  CommentSms,
  CompactDisc,
  Compass2,
  CompassDrafting,
  Compress,
  CompressAlt,
  CompressArrowsAlt,
  Computer,
  ComputerMouse,
  ConciergeBell,
  ContactBook,
  ContactCard,
  Cookie,
  CookieBite,
  Copy,
  Copyright,
  Couch,
  Cow,
  CreditCard,
  CreditCardAlt,
  Crop,
  CropAlt,
  CropSimple,
  Cross,
  Crosshairs,
  Crow,
  Crown,
  Crutch,
  CruzeiroSign,
  Cube,
  Cubes,
  CubesStacked,
  Cut,
  Cutlery,
  Dashboard,
  Database,
  Deaf,
  Deafness,
  Dedent,
  DeleteLeft,
  Democrat,
  Desktop,
  DesktopAlt,
  Dharmachakra,
  Diagnoses,
  DiagramNext,
  DiagramPredecessor,
  DiagramProject,
  DiagramSuccessor,
  Diamond,
  DiamondTurnRight,
  Dice,
  DiceD20,
  DiceD6,
  DiceFive,
  DiceFour,
  DiceOne,
  DiceSix,
  DiceThree,
  DiceTwo,
  Digging,
  DigitalTachograph,
  Directions,
  Disease,
  Display,
  Divide,
  Dizzy,
  Dletter,
  Dna,
  Dog,
  Dollar,
  DollarSign,
  Dolly,
  DollyBox,
  DollyFlatbed,
  Donate,
  DongSign,
  DoorClosed,
  DoorOpen,
  DotCircle,
  Dove,
  DownLeftAndUpRightToCenter,
  Download,
  DownLong,
  DraftingCompass,
  Dragon,
  DrawPolygon,
  DriversLicense,
  Droplet,
  DropletSlash,
  Drum,
  DrumSteelpan,
  DrumstickBite,
  Dumbbell,
  Dumpster,
  DumpsterFire,
  Dungeon,
  EarDeaf,
  EarListen,
  Earth,
  EarthAfrica,
  EarthAmerica,
  EarthAmericas,
  EarthAsia,
  EarthEurope,
  EarthOceania,
  Edit,
  Egg,
  Eject,
  Eletter,
  Elevator,
  Ellipsis,
  EllipsisH,
  EllipsisV,
  EllipsisVertical,
  Envelope,
  EnvelopeCircleCheck,
  EnvelopeOpen,
  EnvelopeOpenText,
  EnvelopesBulk,
  EnvelopeSquare,
  Equals,
  Eraser,
  Ethernet,
  Eur,
  Euro,
  EuroSign,
  Exchange,
  ExchangeAlt,
  Exclamation,
  ExclamationCircle,
  ExclamationTriangle,
  Expand,
  ExpandAlt,
  ExpandArrowsAlt,
  Explosion,
  ExternalLink,
  ExternalLinkAlt,
  ExternalLinkSquare,
  ExternalLinkSquareAlt,
  Eye,
  EyeDropper,
  Eyedropper,
  EyeDropperEmpty,
  EyeLowVision,
  EyeSlash,
  FaceAngry,
  FaceDizzy,
  FaceFlushed,
  FaceFrown,
  FaceFrownOpen,
  FaceGrimace,
  FaceGrin,
  FaceGrinBeam,
  FaceGrinBeamSweat,
  FaceGrinHearts,
  FaceGrinSquint,
  FaceGrinSquintTears,
  FaceGrinStars,
  FaceGrinTears,
  FaceGrinTongue,
  FaceGrinTongueSquint,
  FaceGrinTongueWink,
  FaceGrinWide,
  FaceGrinWink,
  FaceKiss,
  FaceKissBeam,
  FaceKissWinkHeart,
  FaceLaugh,
  FaceLaughBeam,
  FaceLaughSquint,
  FaceLaughWink,
  FaceMeh,
  FaceMehBlank,
  FaceRollingEyes,
  FaceSadCry,
  FaceSadTear,
  FaceSmile,
  FaceSmileBeam,
  FaceSmileWink,
  FaceSurprise,
  FaceTired,
  Fan,
  FastBackward,
  FastForward,
  Faucet,
  FaucetDrip,
  Fax,
  Feather,
  FeatherAlt,
  FeatherPointed,
  Feed,
  Female,
  Ferry,
  FighterJet,
  File2,
  FileAlt,
  FileArchive,
  FileArrowDown,
  FileArrowUp,
  FileAudio,
  FileCircleCheck,
  FileCircleExclamation,
  FileCircleMinus,
  FileCirclePlus,
  FileCircleQuestion,
  FileCircleXmark,
  FileClipboard,
  FileCode,
  FileContract,
  FileCsv,
  FileDownload,
  FileEdit,
  FileExcel,
  FileExport,
  FileFragment,
  FileHalfDashed,
  FileImage,
  FileImport,
  FileInvoice,
  FileInvoiceDollar,
  FileLines,
  FileMedical,
  FileMedicalAlt,
  FilePdf,
  FilePen,
  FilePowerpoint,
  FilePrescription,
  FileShield,
  FileSignature,
  FileText,
  FileUpload,
  FileVideo,
  FileWaveform,
  FileWord,
  FileZipper,
  Fill,
  FillDrip,
  Film,
  Filter,
  FilterCircleDollar,
  FilterCircleXmark,
  Fingerprint,
  Fire,
  FireAlt,
  FireBurner,
  FireExtinguisher,
  FireFlameCurved,
  FireFlameSimple,
  FirstAid,
  Fish,
  FishFins,
  FistRaised,
  Flag,
  FlagCheckered,
  FlagUsa,
  Flask,
  FlaskVial,
  Fletter,
  FloppyDisk,
  FlorinSign,
  Flushed,
  Folder,
  FolderBlank,
  FolderClosed,
  FolderMinus,
  FolderOpen,
  FolderPlus,
  FolderTree,
  Font,
  FontAwesome,
  FontAwesomeFlag,
  FontAwesomeLogoFull,
  Football,
  FootballBall,
  Forward,
  ForwardFast,
  ForwardStep,
  FrancSign,
  Frog,
  Frown,
  FrownOpen,
  FunnelDollar,
  Futbol,
  FutbolBall,
  num0,
  num1,
  num2,
  num3,
  num4,
  num5,
  num6,
  num7,
  num8,
  num9,
} from "./FontAwesome";
import {
  Gamepad3,
  GasPump,
  Gauge,
  GaugeHigh,
  GaugeMed,
  GaugeSimple,
  GaugeSimpleHigh,
  GaugeSimpleMed,
  Gavel,
  Gbp,
  Gear,
  Gears,
  Gem,
  Genderless,
  Ghost,
  Gift,
  Gifts,
  GlassCheers,
  Glasses,
  GlassMartini,
  GlassMartiniAlt,
  GlassWater,
  GlassWaterDroplet,
  GlassWhiskey,
  Gletter,
  Globe,
  GlobeAfrica,
  GlobeAmericas,
  GlobeAsia,
  GlobeEurope,
  GlobeOceania,
  GolfBall,
  GolfBallTee,
  Gopuram,
  GraduationCap,
  GreaterThan,
  GreaterThanEqual,
  Grimace,
  Grin,
  GrinAlt,
  GrinBeam,
  GrinBeamSweat,
  GrinHearts,
  GrinSquint,
  GrinSquintTears,
  GrinStars,
  GrinTears,
  GrinTongue,
  GrinTongueSquint,
  GrinTongueWink,
  GrinWink,
  Grip,
  GripHorizontal,
  GripLines,
  GripLinesVertical,
  GripVertical,
  GroupArrowsRotate,
  GuaraniSign,
  Guitar,
  Gun,
  Hamburger,
  Hammer,
  Hamsa,
  Hand,
  HandBackFist,
  Handcuffs,
  HandDots,
  HandFist,
  HandHolding,
  HandHoldingDollar,
  HandHoldingDroplet,
  HandHoldingHand,
  HandHoldingHeart,
  HandHoldingMedical,
  HandHoldingUsd,
  HandHoldingWater,
  HandLizard,
  HandMiddleFinger,
  HandPaper,
  HandPeace,
  HandPointDown,
  HandPointer,
  HandPointLeft,
  HandPointRight,
  HandPointUp,
  HandRock,
  Hands,
  HandsAmericanSignLanguageInterpreting,
  HandsAslInterpreting,
  HandsBound,
  HandsBubbles,
  HandScissors,
  HandsClapping,
  Handshake,
  HandshakeAlt,
  HandshakeAltSlash,
  HandshakeAngle,
  HandshakeSimple,
  HandshakeSimpleSlash,
  HandshakeSlash,
  HandsHelping,
  HandsHolding,
  HandsHoldingChild,
  HandsHoldingCircle,
  HandSparkles,
  HandSpock,
  HandsPraying,
  HandsWash,
  Hanukiah,
  HardDrive,
  HardHat,
  HardOfHearing,
  Hashtag,
  HatCowboy,
  HatCowboySide,
  HatHard,
  HatWizard,
  Haykal,
  Hdd,
  Header,
  Heading,
  Headphones,
  HeadphonesAlt,
  HeadphonesSimple,
  Headset,
  HeadSideCough,
  HeadSideCoughSlash,
  HeadSideMask,
  HeadSideVirus,
  Heart,
  Heartbeat,
  HeartBroken,
  HeartCircleBolt,
  HeartCircleCheck,
  HeartCircleExclamation,
  HeartCircleMinus,
  HeartCirclePlus,
  HeartCircleXmark,
  HeartCrack,
  HeartMusicCameraBolt,
  HeartPulse,
  Helicopter,
  HelicopterSymbol,
  HelmetSafety,
  HelmetUn,
  HexagonNodes,
  HexagonNodesBolt,
  Highlighter,
  Hiking,
  HillAvalanche,
  HillRockslide,
  Hippo,
  History2,
  Hletter,
  HockeyPuck,
  HollyBerry,
  Home,
  HomeAlt,
  HomeLg,
  HomeLgAlt,
  HomeUser,
  Horse,
  HorseHead,
  Hospital,
  HospitalAlt,
  HospitalSymbol,
  HospitalUser,
  HospitalWide,
  Hotdog,
  Hotel,
  HotTub,
  HotTubPerson,
  Hourglass,
  Hourglass1,
  Hourglass2,
  Hourglass3,
  HourglassEmpty,
  HourglassEnd,
  HourglassHalf,
  HourglassStart,
  House,
  HouseChimney,
  HouseChimneyCrack,
  HouseChimneyMedical,
  HouseChimneyUser,
  HouseChimneyWindow,
  HouseCircleCheck,
  HouseCircleExclamation,
  HouseCircleXmark,
  HouseCrack,
  HouseDamage,
  HouseFire,
  HouseFlag,
  HouseFloodWater,
  HouseFloodWaterCircleArrowRight,
  HouseLaptop,
  HouseLock,
  HouseMedical,
  HouseMedicalCircleCheck,
  HouseMedicalCircleExclamation,
  HouseMedicalCircleXmark,
  HouseMedicalFlag,
  HouseSignal,
  HouseTsunami,
  HouseUser,
  Hryvnia,
  HryvniaSign,
  HSquare,
  Hurricane,
  IceCream,
  Icicles,
  Icons,
  ICursor,
  IdBadge,
  IdCard,
  IdCardAlt,
  IdCardClip,
  Igloo,
  Iletter,
  Ils,
  Image2,
  ImagePortrait,
  Images,
  Inbox,
  Indent,
  IndianRupee,
  IndianRupeeSign,
  Industry,
  Infinity2,
  Info,
  InfoCircle,
  Inr,
  Institution,
  Italic,
  Jar,
  JarWheat,
  Jedi,
  JetFighter,
  JetFighterUp,
  Joint,
  JournalWhills,
  Jpy,
  JugDetergent,
  Kaaba,
  Key,
  Keyboard,
  Khanda,
  KipSign,
  Kiss,
  KissBeam,
  KissWinkHeart,
  KitchenSet,
  KitMedical,
  KiwiBird,
  Kletter,
  Krw,
  LadderWater,
  Landmark,
  LandmarkAlt,
  LandmarkDome,
  LandmarkFlag,
  LandMineOn,
  Language,
  Laptop,
  LaptopCode,
  LaptopFile,
  LaptopHouse,
  LaptopMedical,
  LariSign,
  Laugh,
  LaughBeam,
  LaughSquint,
  LaughWink,
  LayerGroup,
  Leaf,
  LeftLong,
  LeftRight,
  Legal,
  Lemon,
  LessThan,
  LessThanEqual,
  LevelDown,
  LevelDownAlt,
  LevelUp,
  LevelUpAlt,
  LifeRing,
  Lightbulb,
  LineChart,
  LinesLeaning,
  Link,
  LinkSlash,
  LiraSign,
  List,
  List12,
  ListAlt,
  ListCheck,
  ListDots,
  ListNumeric,
  ListOl,
  ListSquares,
  ListUl,
  LitecoinSign,
  Lletter,
  Location2,
  LocationArrow,
  LocationCrosshairs,
  LocationDot,
  LocationPin,
  LocationPinLock,
  Lock3,
  LockOpen,
  Locust,
  LongArrowAltDown,
  LongArrowAltLeft,
  LongArrowAltRight,
  LongArrowAltUp,
  LongArrowDown,
  LongArrowLeft,
  LongArrowRight,
  LongArrowUp,
  LowVision,
  LuggageCart,
  Lungs,
  LungsVirus,
  Magic,
  MagicWandSparkles,
  Magnet,
  MagnifyingGlass,
  MagnifyingGlassArrowRight,
  MagnifyingGlassChart,
  MagnifyingGlassDollar,
  MagnifyingGlassLocation,
  MagnifyingGlassMinus,
  MagnifyingGlassPlus,
  MailBulk,
  MailForward,
  MailReply,
  MailReplyAll,
  Male,
  ManatSign,
  Map2,
  MapLocation,
  MapLocationDot,
  MapMarked,
  MapMarkedAlt,
  MapMarker,
  MapMarkerAlt,
  MapPin,
  MapSigns,
  Marker,
  Mars,
  MarsAndVenus,
  MarsAndVenusBurst,
  MarsDouble,
  MarsStroke,
  MarsStrokeH,
  MarsStrokeRight,
  MarsStrokeUp,
  MarsStrokeV,
  MartiniGlass,
  MartiniGlassCitrus,
  MartiniGlassEmpty,
  Mask,
  MaskFace,
  MasksTheater,
  MaskVentilator,
  MattressPillow,
  Maximize,
  Medal,
  Medkit,
  Meh,
  MehBlank,
  MehRollingEyes,
  Memory,
  Menorah,
  Mercury,
  Message,
  Meteor,
  Microchip,
  Microphone,
  MicrophoneAlt,
  MicrophoneAltSlash,
  MicrophoneLines,
  MicrophoneLinesSlash,
  MicrophoneSlash,
  Microscope,
  MillSign,
  Minimize,
  Minus,
  MinusCircle,
  MinusSquare,
  Mitten,
  Mletter,
  Mobile,
  MobileAlt,
  MobileAndroid,
  MobileAndroidAlt,
  MobileButton,
  MobilePhone,
  MobileRetro,
  MobileScreen,
  MobileScreenButton,
  MoneyBill,
  MoneyBill1,
  MoneyBill1Wave,
  MoneyBillAlt,
  MoneyBills,
  MoneyBillTransfer,
  MoneyBillTrendUp,
  MoneyBillWave,
  MoneyBillWaveAlt,
  MoneyBillWheat,
  MoneyCheck,
  MoneyCheckAlt,
  MoneyCheckDollar,
  Monument,
  Moon,
  MortarBoard,
  MortarPestle,
  Mosque,
  Mosquito,
  MosquitoNet,
  Motorcycle,
  Mound,
  Mountain,
  MountainCity,
  MountainSun,
  Mouse,
  MousePointer,
  MugHot,
  MugSaucer,
  Multiply,
  Museum,
  Music,
  NairaSign,
  Navicon,
  NetworkWired,
  Neuter,
  Newspaper,
  Nletter,
  Notdef,
  NotEqual,
  NotesMedical,
  NoteSticky,
  ObjectGroup,
  ObjectUngroup,
  OilCan,
  OilWell,
  Oletter,
  Om,
  Otter,
  Outdent,
  Pager,
  PaintBrush,
  Paintbrush,
  PaintRoller,
  Palette,
  Pallet,
  Panorama,
  Paperclip,
  PaperPlane,
  ParachuteBox,
  Paragraph,
  Parking,
  Passport,
  Pastafarianism,
  Paste,
  Pause,
  PauseCircle,
  Paw,
  Peace,
  Pen,
  PenAlt,
  Pencil,
  PencilAlt,
  PencilRuler,
  PencilSquare,
  PenClip,
  PenFancy,
  PenNib,
  PenRuler,
  PenSquare,
  PenToSquare,
  PeopleArrows,
  PeopleArrowsLeftRight,
  PeopleCarry,
  PeopleCarryBox,
  PeopleGroup,
  PeopleLine,
  PeoplePulling,
  PeopleRobbery,
  PeopleRoof,
  PepperHot,
  Percent,
  Percentage,
  Person,
  PersonArrowDownToLine,
  PersonArrowUpFromLine,
  PersonBiking,
  PersonBooth,
  PersonBreastfeeding,
  PersonBurst,
  PersonCane,
  PersonChalkboard,
  PersonCircleCheck,
  PersonCircleExclamation,
  PersonCircleMinus,
  PersonCirclePlus,
  PersonCircleQuestion,
  PersonCircleXmark,
  PersonDigging,
  PersonDotsFromLine,
  PersonDress,
  PersonDressBurst,
  PersonDrowning,
  PersonFalling,
  PersonFallingBurst,
  PersonHalfDress,
  PersonHarassing,
  PersonHiking,
  PersonMilitaryPointing,
  PersonMilitaryRifle,
  PersonMilitaryToPerson,
  PersonPraying,
  PersonPregnant,
  PersonRays,
  PersonRifle,
  PersonRunning,
  PersonShelter,
  PersonSkating,
  PersonSkiing,
  PersonSkiingNordic,
  PersonSnowboarding,
  PersonSwimming,
  PersonThroughWindow,
  PersonWalking,
  PersonWalkingArrowLoopLeft,
  PersonWalkingArrowRight,
  PersonWalkingDashedLineArrowRight,
  PersonWalkingLuggage,
  PersonWalkingWithCane,
  PesetaSign,
  PesoSign,
  Phone,
  Pletter,
} from "./FontAwesome2";
import {
  PhoneAlt,
  PhoneFlip,
  PhoneSlash,
  PhoneSquare,
  PhoneSquareAlt,
  PhoneVolume,
  PhotoFilm,
  PhotoVideo,
  PieChart2,
  PiggyBank2,
  Pills,
  PingPongPaddleBall,
  PizzaSlice,
  PlaceOfWorship,
  Plane2,
  PlaneArrival,
  PlaneCircleCheck,
  PlaneCircleExclamation,
  PlaneCircleXmark,
  PlaneDeparture,
  PlaneLock,
  PlaneSlash,
  PlaneUp,
  PlantWilt,
  PlateWheat,
  Play2,
  PlayCircle2,
  Plug2,
  PlugCircleBolt,
  PlugCircleCheck,
  PlugCircleExclamation,
  PlugCircleMinus,
  PlugCirclePlus,
  PlugCircleXmark,
  Plus2,
  PlusCircle2,
  PlusMinus,
  PlusSquare2,
  Podcast2,
  Poll,
  PollH,
  Poo,
  PooBolt,
  Poop,
  PooStorm,
  Portrait,
  PoundSign,
  PowerOff,
  Pray,
  PrayingHands,
  Prescription,
  PrescriptionBottle,
  PrescriptionBottleAlt,
  PrescriptionBottleMedical,
  Print,
  Procedures,
  ProjectDiagram,
  PumpMedical,
  PumpSoap,
  PuzzlePiece,
  Qletter,
  Qrcode,
  Question,
  QuestionCircle,
  Quidditch,
  QuidditchBroomBall,
  QuoteLeft,
  QuoteLeftAlt,
  QuoteRight,
  QuoteRightAlt,
  Quran,
  Radiation,
  RadiationAlt,
  Radio,
  Rainbow,
  Random,
  RankingStar,
  Receipt,
  RecordVinyl,
  RectangleAd,
  RectangleList,
  RectangleTimes,
  RectangleXmark,
  Recycle,
  Redo,
  RedoAlt,
  Refresh,
  Registered,
  Remove,
  RemoveFormat,
  Reorder,
  Repeat,
  Reply,
  ReplyAll,
  Republican,
  Restroom,
  Retweet,
  Ribbon,
  RightFromBracket,
  RightLeft,
  RightLong,
  RightToBracket,
  Ring,
  Rletter,
  Rmb,
  Road,
  RoadBarrier,
  RoadBridge,
  RoadCircleCheck,
  RoadCircleExclamation,
  RoadCircleXmark,
  RoadLock,
  RoadSpikes,
  Robot,
  Rocket,
  RodAsclepius,
  RodSnake,
  Rotate,
  RotateBack,
  RotateBackward,
  RotateForward,
  RotateLeft,
  RotateRight,
  Rouble,
  Route,
  Rss,
  RssSquare,
  Rub,
  Ruble,
  RubleSign,
  Rug,
  Ruler,
  RulerCombined,
  RulerHorizontal,
  RulerVertical,
  Running,
  Rupee,
  RupeeSign,
  RupiahSign,
  SackDollar,
  SackXmark,
  SadCry,
  SadTear,
  Sailboat,
  Satellite,
  SatelliteDish,
  Save,
  ScaleBalanced,
  ScaleUnbalanced,
  ScaleUnbalancedFlip,
  School,
  SchoolCircleCheck,
  SchoolCircleExclamation,
  SchoolCircleXmark,
  SchoolFlag,
  SchoolLock,
  Scissors,
  Screwdriver,
  ScrewdriverWrench,
  Scroll,
  ScrollTorah,
  SdCard,
  Search,
  SearchDollar,
  SearchLocation,
  SearchMinus,
  SearchPlus,
  Section,
  Seedling,
  Server,
  Shapes,
  Share,
  ShareAlt,
  ShareAltSquare,
  ShareFromSquare,
  ShareNodes,
  ShareSquare,
  SheetPlastic,
  Shekel,
  ShekelSign,
  Sheqel,
  SheqelSign,
  Shield,
  ShieldAlt,
  ShieldBlank,
  ShieldCat,
  ShieldDog,
  ShieldHalved,
  ShieldHeart,
  ShieldVirus,
  Ship,
  ShippingFast,
  Shirt,
  ShoePrints,
  Shop,
  ShopLock,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  ShopSlash,
  Shower,
  Shrimp,
  Shuffle,
  ShuttleSpace,
  ShuttleVan,
  Sign,
  Signal,
  Signal5,
  SignalPerfect,
  Signature,
  SignHanging,
  SignIn,
  SignInAlt,
  Signing,
  SignLanguage,
  SignOut,
  SignOutAlt,
  SignsPost,
  SimCard,
  Sink,
  Sitemap,
  Skating,
  Skiing,
  SkiingNordic,
  Skull,
  SkullCrossbones,
  Slash,
  Sleigh,
  Sletter,
  Sliders,
  SlidersH,
  Smile,
  SmileBeam,
  SmileWink,
  Smog,
  Smoking,
  SmokingBan,
  Sms,
  Snowboarding,
  Snowflake,
  Snowman,
  Snowplow,
  Soap,
  SoccerBall,
  Socks,
  SolarPanel,
  Sort,
  SortAlphaAsc,
  SortAlphaDesc,
  SortAlphaDown,
  SortAlphaDownAlt,
  SortAlphaUp,
  SortAlphaUpAlt,
  SortAmountAsc,
  SortAmountDesc,
  SortAmountDown,
  SortAmountDownAlt,
  SortAmountUp,
  SortAmountUpAlt,
  SortAsc,
  SortDesc,
  SortDown,
  SortNumericAsc,
  SortNumericDesc,
  SortNumericDown,
  SortNumericDownAlt,
  SortNumericUp,
  SortNumericUpAlt,
  SortUp,
  Spa,
  SpaceShuttle,
  SpaghettiMonsterFlying,
  SpellCheck,
  Spider,
  Spinner,
  Splotch,
  Spoon,
  SprayCan,
  SprayCanSparkles,
  Sprout,
  Square,
  SquareArrowUpRight,
  SquareBinary,
  SquareCaretDown,
  SquareCaretLeft,
  SquareCaretRight,
  SquareCaretUp,
  SquareCheck,
  SquareEnvelope,
  SquareFull,
  SquareH,
  SquareMinus,
  SquareNfi,
  SquareParking,
  SquarePen,
  SquarePersonConfined,
  SquarePhone,
  SquarePhoneFlip,
  SquarePlus,
  SquarePollHorizontal,
  SquarePollVertical,
  SquareRootAlt,
  SquareRootVariable,
  SquareRss,
  SquareShareNodes,
  SquareUpRight,
  SquareVirus,
  SquareXmark,
  StaffAesculapius,
  StaffSnake,
  Stairs,
  Stamp,
  Stapler,
  Star,
  StarAndCrescent,
  StarHalf,
  StarHalfAlt,
  StarHalfStroke,
  StarOfDavid,
  StarOfLife,
  StepBackward,
  StepForward,
  SterlingSign,
  Stethoscope,
  StickyNote,
  Stop,
  StopCircle,
  Stopwatch,
  Stopwatch20,
  Store,
  StoreAlt,
  StoreAltSlash,
  StoreSlash,
  Stream,
  StreetView,
  Strikethrough,
  Stroopwafel,
  Subscript,
  Subtract,
  Subway,
  Suitcase,
  SuitcaseMedical,
  SuitcaseRolling,
  Sun,
  SunPlantWilt,
  Superscript,
  Surprise,
  Swatchbook,
  Swimmer,
  SwimmingPool,
  Synagogue,
  Sync,
  SyncAlt,
  Syringe,
  Table,
  TableCells,
  TableCellsColumnLock,
  TableCellsLarge,
  TableCellsRowLock,
  TableCellsRowUnlock,
  TableColumns,
  TableList,
  Tablet,
  TabletAlt,
  TabletAndroid,
  TabletButton,
  TableTennis,
  TableTennisPaddleBall,
  Tablets,
  TabletScreenButton,
  TachographDigital,
  Tachometer,
  TachometerAlt,
  TachometerAltAverage,
  TachometerAltFast,
  TachometerAverage,
  TachometerFast,
  Tag,
  Tags,
  Tanakh,
  Tape,
  Tarp,
  TarpDroplet,
  Tasks,
  TasksAlt,
  Taxi,
  Teeth,
  TeethOpen,
  Teletype,
  Television,
  Temperature0,
  Temperature1,
  Temperature2,
  Temperature3,
  Temperature4,
  TemperatureArrowDown,
  TemperatureArrowUp,
  TemperatureDown,
  TemperatureEmpty,
  TemperatureFull,
  TemperatureHalf,
  TemperatureHigh,
  TemperatureLow,
  TemperatureQuarter,
  TemperatureThreeQuarters,
  TemperatureUp,
  Tenge,
  TengeSign,
  Tent,
  TentArrowDownToLine,
  TentArrowLeftRight,
  TentArrowsDown,
  TentArrowTurnLeft,
  Tents,
  Terminal,
  TextHeight,
  TextSlash,
  TextWidth,
  Th,
  TheaterMasks,
  Thermometer,
  Thermometer0,
  Thermometer1,
  Thermometer2,
  Thermometer3,
  Thermometer4,
  ThermometerEmpty,
  ThermometerFull,
  ThermometerHalf,
  ThermometerQuarter,
  ThermometerThreeQuarters,
  ThLarge,
  ThList,
  ThumbsDown,
  ThumbsUp,
  ThumbTack,
  ThumbTackSlash,
  Thunderstorm,
  Ticket,
  TicketAlt,
  TicketSimple,
  Timeline,
  Times,
  TimesCircle,
  TimesRectangle,
  TimesSquare,
  Tint,
  TintSlash,
  Tired,
  Tletter,
  ToggleOff,
  ToggleOn,
  Toilet,
  ToiletPaper,
  ToiletPaperSlash,
  ToiletPortable,
  ToiletsPortable,
  Toolbox,
  Tools,
  Tooth,
  Torah,
  ToriiGate,
  Tornado,
  TowerBroadcast,
  TowerCell,
  TowerObservation,
  Tractor,
  Trademark,
  TrafficLight,
  Trailer,
  Train,
  TrainSubway,
  TrainTram,
  Tram,
  Transgender,
  TransgenderAlt,
  Trash,
  TrashAlt,
  TrashArrowUp,
  TrashCan,
  TrashCanArrowUp,
  TrashRestore,
  TrashRestoreAlt,
  Tree,
  TreeCity,
  TShirt,
} from "./FontAwesome3";
import {
  TriangleCircleSquare,
  TriangleExclamation,
  Trophy2,
  Trowel,
  TrowelBricks,
  Truck2,
  TruckArrowRight,
  TruckDroplet,
  TruckFast,
  TruckField,
  TruckFieldUn,
  TruckFront,
  TruckLoading,
  TruckMedical,
  TruckMonster,
  TruckMoving,
  TruckPickup,
  TruckPlane,
  TruckRampBox,
  Try,
  Tshirt,
  Tty,
  TurkishLira,
  TurkishLiraSign,
  TurnDown,
  TurnUp,
  Tv2,
  TvAlt,
  Uletter,
  Umbrella,
  UmbrellaBeach,
  Underline,
  Undo,
  UndoAlt,
  UniversalAccess,
  University,
  Unlink,
  Unlock,
  UnlockAlt,
  UnlockKeyhole,
  Unsorted,
  UpDown,
  UpDownLeftRight,
  Upload,
  UpLong,
  UpRightAndDownLeftFromCenter,
  UpRightFromSquare,
  Usd,
  User,
  UserAlt,
  UserAltSlash,
  UserAstronaut,
  UserCheck,
  UserCircle,
  UserClock,
  UserCog,
  UserDoctor,
  UserEdit,
  UserFriends,
  UserGear,
  UserGraduate,
  UserGroup,
  UserInjured,
  UserLarge,
  UserLargeSlash,
  UserLock,
  UserMd,
  UserMinus,
  UserNinja,
  UserNurse,
  UserPen,
  UserPlus,
  Users,
  UsersBetweenLines,
  UsersCog,
  UserSecret,
  UsersGear,
  UserShield,
  UserSlash,
  UsersLine,
  UsersRays,
  UsersRectangle,
  UsersSlash,
  UsersViewfinder,
  UserTag,
  UserTie,
  UserTimes,
  UserXmark,
  Utensils,
  UtensilSpoon,
  VanShuttle,
  Vault,
  Vcard,
  VectorSquare,
  Venus,
  VenusDouble,
  VenusMars,
  Vest,
  VestPatches,
  Vial,
  VialCircleCheck,
  Vials,
  VialVirus,
  Video,
  VideoCamera,
  VideoSlash,
  Vihara,
  Virus,
  VirusCovid,
  VirusCovidSlash,
  Viruses,
  VirusSlash,
  Vletter,
  Voicemail,
  Volcano,
  Volleyball,
  VolleyballBall,
  VolumeControlPhone,
  VolumeDown,
  VolumeHigh,
  VolumeLow,
  VolumeMute,
  VolumeOff,
  VolumeTimes,
  VolumeUp,
  VolumeXmark,
  VoteYea,
  VrCardboard,
  WalkieTalkie,
  Walking,
  Wallet,
  Warehouse,
  Warning,
  Water,
  WaterLadder,
  WaveSquare,
  WebAwesome,
  Weight,
  WeightHanging,
  WeightScale,
  WheatAlt,
  WheatAwn,
  WheatAwnCircleExclamation,
  Wheelchair,
  WheelchairAlt,
  WheelchairMove,
  WhiskeyGlass,
  Wifi,
  Wifi3,
  WifiStrong,
  Wind,
  WindowClose,
  WindowMaximize,
  WindowMinimize,
  WindowRestore,
  WineBottle,
  WineGlass,
  WineGlassAlt,
  WineGlassEmpty,
  Wletter,
  Won,
  WonSign,
  Worm,
  Wrench,
  Xletter,
  Xmark,
  XmarkCircle,
  XmarksLines,
  XmarkSquare,
  XRay,
  Yen,
  YenSign,
  YinYang,
  Yletter,
  Zap,
  Zletter,
} from "./FontAwesome4";

// // // props
interface IconsProps {
  className?: string;
}

export const AwesomeIconsMap: Record<string, React.FC<IconsProps>> = {
  letterA: Aletter,
  number0: num0,
  number1: num1,
  number2: num2,
  number3: num3,
  number4: num4,
  number5: num5,
  number6: num6,
  number7: num7,
  number8: num8,
  number9: num9,
  Ad: Ad,
  plus: Add,
  AddressBook: AddressBook,
  AddressCard: AddressCard,
  Adjust: Adjust,
  AirFreshenerCleaning: AirFreshener,
  AlignCenter: AlignCenter2,
  AlignJustify: AlignJustify2,
  AlignLeft: AlignLeft2,
  AlignRight: AlignRight2,
  Allergies: Allergies,
  Ambulance: Ambulance,
  AmericanSignLanguageInterpreting: AmericanSignLanguageInterpreting,
  anchor: Anchor2,
  AnchorCircleCheck: AnchorCircleCheck,
  AnchorCircleExclamation: AnchorCircleExclamation,
  AnchorCircleXmark: AnchorCircleXmark,
  AnchorLock: AnchorLock,
  AngleDoubleDown: AngleDoubleDown,
  AngleDoubleLeft: AngleDoubleLeft,
  AngleDoubleRight: AngleDoubleRight,
  AngleDoubleUp: AngleDoubleUp,
  AngleDown: AngleDown,
  AngleLeft: AngleLeft,
  AngleRight: AngleRight,
  AngleUp: AngleUp,
  AnglesDown: AnglesDown,
  AnglesLeft: AnglesLeft,
  AnglesRight: AnglesRight,
  AnglesUp: AnglesUp,
  AngryFace: Angry,
  AnkhSymbol: Ankh,
  AppleWholeCompany: AppleWhole,
  archive: Archive2,
  Archway: Archway,
  AreaChart: AreaChart,
  ArrowAltCircleDown: ArrowAltCircleDown,
  ArrowAltCircleLeft: ArrowAltCircleLeft,
  ArrowAltCircleRight: ArrowAltCircleRight,
  ArrowAltCircleUp: ArrowAltCircleUp,
  ArrowCircleDown: ArrowAltCircleDown,
  ArrowCircleLeft: ArrowAltCircleLeft,
  ArrowCircleRight: ArrowAltCircleRight,
  ArrowCircleUp: ArrowAltCircleUp,
  ArrowRightArrowLeft: ArrowRightArrowLeft,
  ArrowRightFromBracket: ArrowRightFromBracket,
  ArrowRightFromFile: ArrowRightFromFile,
  ArrowRightLong: ArrowRightLong,
  ArrowRightRotate: ArrowRightRotate,
  ArrowRightToBracket: ArrowRightToBracket,
  ArrowRightToCity: ArrowRightToCity,
  ArrowRightToFile: ArrowRightToFile,
  ArrowRotateBack: ArrowRotateBack,
  ArrowRotateBackward: ArrowRotateBackward,
  ArrowRotateForward: ArrowRotateForward,
  ArrowRotateLeft: ArrowRotateLeft,
  ArrowRotateRight: ArrowRotateRight,
  ArrowTrendDown: ArrowTrendDown,
  ArrowTrendUp: ArrowTrendUp,
  ArrowTurnDown: ArrowTurnDown,
  ArrowTurnUp: ArrowTurnUp,
  ArrowUp19: ArrowUp19,
  ArrowUp91: ArrowUp91,
  ArrowUpAZ: ArrowUpAZ,
  ArrowUpFromBracket: ArrowUpFromBracket,
  ArrowUpFromGroundWater: ArrowUpFromGroundWater,
  ArrowUpFromWaterPump: ArrowUpFromWaterPump,
  ArrowUpLong: ArrowUpLong,
  ArrowUpRightDots: ArrowUpRightDots,
  ArrowUpRightFromSquare: ArrowUpRightFromSquare,
  ArrowUpShortWide: ArrowUpShortWide,
  ArrowUpWideShort: ArrowUpWideShort,
  ArrowUpZA: ArrowUpZA,
  Arrows: Arrows,
  ArrowsAlt: ArrowsAlt,
  ArrowsAltH: ArrowsAltH,
  ArrowsAltV: ArrowsAltV,
  ArrowsDownToLine: ArrowsDownToLine,
  ArrowsDownToPeople: ArrowsDownToPeople,
  ArrowsLeftRight: ArrowsLeftRight,
  ArrowsRotate: ArrowsRotate,
  ArrowsUpDown: ArrowsUpDown,
  AslInterpreting: AslInterpreting,
  AssistiveListeningSystems: AssistiveListeningSystems,
  Asterisk: Asterisk,
  At: At,
  AtlasBook: Atlas,
  AtomSymbol: Atom,
  AudioDescription: AudioDescription,
  AustralSign: AustralSign,
  AutomobileCar: Automobile,
  Award: Award2,
  letterB: Bletter,
  Baby: Baby,
  BabyCarriage: BabyCarriage,
  Backspace: Backspace,
  Backward: Backward,
  BackwardFast: BackwardFast,
  BackwardStep: BackwardStep,
  BaconFood: Bacon,
  Bacteria: Bacteria,
  Bacterium: Bacterium,
  BagShopping: BagShopping,
  BahaiSymbol: Bahai,
  BahtSign: BahtSign,
  BalanceScale: BalanceScale,
  BalanceScaleLeft: BalanceScaleLeft,
  BalanceScaleRight: BalanceScaleRight,
  Ban: Ban,
  BanSmoking: BanSmoking,
  BandAid: BandAid,
  BookMedical: BookMedical,
  BookOpen: BookOpen,
  BookOpenReader: BookOpenReader,
  BookQuran: BookQuran,
  BookReader: BookReader,
  BookSkull: BookSkull,
  BookTanakh: BookTanakh,
  Bookmark: Bookmark,
  BorderAll: BorderAll,
  BorderNone: BorderNone,
  BorderStyle: BorderStyle,
  BorderTopLeft: BorderTopLeft,
  BoreHole: BoreHole,
  BottleDroplet: BottleDroplet,
  BottleWater: BottleWater,
  BowlFood: BowlFood,
  BowlRice: BowlRice,
  BowlingBall: BowlingBall,
  Box: Box,
  BoxArchive: BoxArchive,
  BoxOpen: BoxOpen,
  BoxTissue: BoxTissue,
  Boxes: Boxes,
  BoxesPacking: BoxesPacking,
  BoxesStacked: BoxesStacked,
  BrailleSign: Braille,
  Brain: Brain,
  BrazilianRealSign: BrazilianRealSign,
  BreadSliceFood: BreadSlice,
  Bridge: Bridge,
  BridgeCircleCheck: BridgeCircleCheck,
  BridgeCircleExclamation: BridgeCircleExclamation,
  BridgeCircleXmark: BridgeCircleXmark,
  BridgeLock: BridgeLock,
  BridgeWater: BridgeWater,
  Briefcase: Briefcase,
  BriefcaseClock: BriefcaseClock,
  BriefcaseMedical: BriefcaseMedical,
  BroadcastTower: BroadcastTower,
  Broom: Broom,
  BroomBall: BroomBall,
  Brush: Brush,
  Bucket: Bucket,
  Bug: Bug,
  BugSlash: BugSlash,
  Bugs: Bugs,
  Building: Building,
  BuildingCircleArrowRight: BuildingCircleArrowRight,
  BuildingCircleCheck: BuildingCircleCheck,
  BuildingCircleExclamation: BuildingCircleExclamation,
  BuildingCircleXmark: BuildingCircleXmark,
  BuildingColumns: BuildingColumns,
  BuildingFlag: BuildingFlag,
  BuildingLock: BuildingLock,
  BuildingNgo: BuildingNgo,
  BuildingShield: BuildingShield,
  BuildingUn: BuildingUn,
  BuildingUser: BuildingUser,
  BuildingWheat: BuildingWheat,
  Bullhorn: Bullhorn,
  Bullseye: Bullseye,
  BurgerFood: Burger,
  FireBurn: Burn,
  Burst: Burst,
  Bus: Bus,
  BusAlt: BusAlt,
  BusSimple: BusSimple,
  BusinessTime: BusinessTime,
  //    // // // // c
  letterC: Cletter,
  CabCar: Cab,
  CableCar: CableCar,
  CakeFood: Cake,
  CakeCandlesFood: CakeCandles,
  Calculator: Calculator,
  Calendar: Calendar,
  CalendarAlt: CalendarAlt,
  CalendarCheck: CalendarCheck,
  CalendarDay: CalendarDay,
  CalendarDays: CalendarDays,
  CalendarMinus: CalendarMinus,
  CalendarPlus: CalendarPlus,
  CalendarTimes: CalendarTimes,
  CalendarWeek: CalendarWeek,
  CalendarXmark: CalendarXmark,
  Camera: Camera,
  CameraAlt: CameraAlt,
  CameraRetro: CameraRetro,
  CameraRotate: CameraRotate,
  Campground: Campground,
  Cancel: Cancel,
  CandyCane: CandyCane,
  CannabisSymbol: Cannabis,
  Capsules: Capsules,
  Car: Car,
  CarAlt: CarAlt,
  CarBattery: CarBattery,
  CarBurst: CarBurst,
  CarCrash: CarCrash,
  CarOn: CarOn,
  CarRear: CarRear,
  CarSide: CarSide,
  CarTunnel: CarTunnel,
  Caravan: Caravan,
  CaretDown: CaretDown,
  CaretLeft: CaretLeft,
  CaretRight: CaretRight,
  CaretSquareDown: CaretSquareDown,
  CaretSquareLeft: CaretSquareLeft,
  CaretSquareRight: CaretSquareRight,
  CaretSquareUp: CaretSquareUp,
  CaretUp: CaretUp,
  CarriageBaby: CarriageBaby,
  CarrotFood: Carrot,
  CartArrowDown: CartArrowDown,
  CartFlatbed: CartFlatbed,
  CartFlatbedSuitcase: CartFlatbedSuitcase,
  CartPlus: CartPlus,
  CartShoppingFood: CartShopping,
  CashRegister: CashRegister,
  CatAnimal: Cat,
  CediSign: CediSign,
  CentSign: CentSign,
  Certificate: Certificate,
  Chain: Chain,
  ChainBroken: ChainBroken,
  ChainSlash: ChainSlash,
  Chair: Chair,
  Chalkboard: Chalkboard,
  ChalkboardTeacher: ChalkboardTeacher,
  ChalkboardUser: ChalkboardUser,
  ChampagneGlassesFood: ChampagneGlasses,
  ChargingStation: ChargingStation,
  ChartArea: ChartArea,
  ChartBar: ChartBar,
  ChartColumn: ChartColumn,
  ChartDiagram: ChartDiagram,
  ChartGantt: ChartGantt,
  ChartLine: ChartLine,
  ChartPie: ChartPie,
  ChartSimple: ChartSimple,
  Check: Check,
  CheckCircle: CheckCircle,
  CheckDouble: CheckDouble,
  CheckSquare: CheckSquare,
  CheckToSlot: CheckToSlot,
  CheeseFood: Cheese,
  Chess: Chess,
  ChessBishop: ChessBishop,
  ChessBoard: ChessBoard,
  ChessKing: ChessKing,
  ChessKnight: ChessKnight,
  ChessPawn: ChessPawn,
  ChessQueen: ChessQueen,
  ChessRook: ChessRook,
  ChevronCircleDown: ChevronCircleDown,
  ChevronCircleLeft: ChevronCircleLeft,
  ChevronCircleRight: ChevronCircleRight,
  ChevronCircleUp: ChevronCircleUp,
  ChevronDown: ChevronDown,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  ChevronUp: ChevronUp,
  Child: Child,
  ChildCombatant: ChildCombatant,
  ChildDress: ChildDress,
  ChildReaching: ChildReaching,
  ChildRifle: ChildRifle,
  Children: Children,
  Church: Church,
  Circle: Circle,
  CircleArrowDown: CircleArrowDown,
  CircleArrowLeft: CircleArrowLeft,
  CircleArrowRight: CircleArrowRight,
  CircleArrowUp: CircleArrowUp,
  CircleCheck: CircleCheck,
  CircleChevronDown: CircleChevronDown,
  CircleChevronLeft: CircleChevronLeft,
  CircleChevronRight: CircleChevronRight,
  CircleChevronUp: CircleChevronUp,
  CircleDollarToSlot: CircleDollarToSlot,
  CircleDot: CircleDot,
  CircleDown: CircleDown,
  CircleExclamation: CircleExclamation,
  CircleH: CircleH,
  CircleHalfStroke: CircleHalfStroke,
  CircleInfo: CircleInfo,
  CircleLeft: CircleLeft,
  CircleMinus: CircleMinus,
  CircleNodes: CircleNodes,
  CircleNotch: CircleNotch,
  CirclePause: CirclePause,
  CirclePlay: CirclePlay,
  CirclePlus: CirclePlus,
  CircleQuestion: CircleQuestion,
  CircleRadiation: CircleRadiation,
  CircleRight: CircleRight,
  CircleStop: CircleStop,
  CircleUp: CircleUp,
  CircleUser: CircleUser,
  CircleXmark: CircleXmark,
  City: City,
  Clapperboard: Clapperboard,
  ClinicMedical: ClinicMedical,
  Clipboard: Clipboard2,
  ClipboardCheck: ClipboardCheck,
  ClipboardList: ClipboardList,
  ClipboardQuestion: ClipboardQuestion,
  ClipboardUser: ClipboardUser,
  Clock: Clock,
  ClockFour: ClockFour,
  ClockRotateLeft: ClockRotateLeft,
  Clone: Clone,
  Close: Close,
  ClosedCaptioning: ClosedCaptioning,
  CloudWeather: Cloud,
  CloudArrowDownWeather: CloudArrowDown,
  CloudArrowUpWeather: CloudArrowUp,
  CloudBoltWeather: CloudBolt,
  CloudDownloadWeather: CloudDownload,
  CloudDownloadAltWeather: CloudDownloadAlt,
  CloudMeatballWeather: CloudMeatball,
  CloudMoonWeather: CloudMoon,
  CloudMoonRainWeather: CloudMoonRain,
  CloudRainWeather: CloudRain,
  CloudShowersHeavyWeather: CloudShowersHeavy,
  CloudShowersWaterWeather: CloudShowersWater,
  CloudSunWeather: CloudSun,
  CloudSunRainWeather: CloudSunRain,
  CloudUploadWeather: CloudUpload,
  CloudUploadAltWeather: CloudUploadAlt,
  CloverSymbol: Clover,
  CnySign: Cny,
  CocktailFood: Cocktail,
  Code: Code,
  CodeBranch: CodeBranch,
  CodeCommit: CodeCommit,
  CodeCompare: CodeCompare,
  CodeFork: CodeFork,
  CodeMerge: CodeMerge,
  CodePullRequest: CodePullRequest,
  CoffeeFood: Coffee2,
  Cog: Cog,
  Cogs: Cogs,
  Coins: Coins,
  ColonSign: ColonSign,
  Columns: Columns,
  Comment: Comment2,
  CommentAlt: CommentAlt,
  CommentDollar: CommentDollar,
  CommentDots: CommentDots,
  CommentMedical: CommentMedical,
  CommentNodes: CommentNodes,
  CommentSlash: CommentSlash,
  CommentSms: CommentSms,
  Commenting: Commenting,
  Comments: Comments,
  CommentsDollar: CommentsDollar,
  CompactDisc: CompactDisc,
  Compass: Compass2,
  CompassDrafting: CompassDrafting,
  Compress: Compress,
  CompressAlt: CompressAlt,
  CompressArrowsAlt: CompressArrowsAlt,
  Computer: Computer,
  ComputerMouse: ComputerMouse,
  ConciergeBell: ConciergeBell,
  ContactBook: ContactBook,
  ContactCard: ContactCard,
  CookieFood: Cookie,
  CookieBiteFood: CookieBite,
  Copy: Copy,
  Copyright: Copyright,
  Couch: Couch,
  CowAnimal: Cow,
  CreditCard: CreditCard,
  CreditCardAlt: CreditCardAlt,
  Crop: Crop,
  CropAlt: CropAlt,
  CropSimple: CropSimple,
  CrossSymbol: Cross,
  Crosshairs: Crosshairs,
  CrowAnimal: Crow,
  CrownSymbol: Crown,
  Crutch: Crutch,
  CruzeiroSign: CruzeiroSign,
  Cube: Cube,
  CubesSymbol: Cubes,
  CubesStacked: CubesStacked,
  Cut: Cut,
  Cutlery: Cutlery,
  //    // // // // // // d
  letterD: Dletter,
  Dashboard: Dashboard,
  Database: Database,
  Deaf: Deaf,
  Deafness: Deafness,
  Dedent: Dedent,
  DeleteLeft: DeleteLeft,
  Democrat: Democrat,
  Desktop: Desktop,
  DesktopAlt: DesktopAlt,
  Dharmachakra: Dharmachakra,
  Diagnoses: Diagnoses,
  DiagramNext: DiagramNext,
  DiagramPredecessor: DiagramPredecessor,
  DiagramProject: DiagramProject,
  DiagramSuccessor: DiagramSuccessor,
  Diamond: Diamond,
  DiamondTurnRight: DiamondTurnRight,
  Dice: Dice,
  DiceD6: DiceD6,
  DiceD20: DiceD20,
  DiceFive: DiceFive,
  DiceFour: DiceFour,
  DiceOne: DiceOne,
  DiceSix: DiceSix,
  DiceThree: DiceThree,
  DiceTwo: DiceTwo,
  Digging: Digging,
  DigitalTachograph: DigitalTachograph,
  Directions: Directions,
  Disease: Disease,
  Display: Display,
  Divide: Divide,
  Dizzy: Dizzy,
  DnaSymbol: Dna,
  Dog: Dog,
  Dollar: Dollar,
  DollarSign: DollarSign,
  Dolly: Dolly,
  DollyBox: DollyBox,
  DollyFlatbed: DollyFlatbed,
  Donate: Donate,
  DongSign: DongSign,
  DoorClosed: DoorClosed,
  DoorOpen: DoorOpen,
  DotCircle: DotCircle,
  Dove: Dove,
  DownLeftAndUpRightToCenter: DownLeftAndUpRightToCenter,
  DownLong: DownLong,
  Download: Download,
  DraftingCompass: DraftingCompass,
  DragonAnimal: Dragon,
  DrawPolygon: DrawPolygon,
  DriversLicense: DriversLicense,
  Droplet: Droplet,
  DropletSlash: DropletSlash,
  DrumMusic: Drum,
  DrumSteelpanMusic: DrumSteelpan,
  DrumstickBiteFood: DrumstickBite,
  Dumbbell: Dumbbell,
  Dumpster: Dumpster,
  DumpsterFire: DumpsterFire,
  Dungeon: Dungeon,
  //   // // // // e
  letterE: Eletter,
  EarDeaf: EarDeaf,
  EarListen: EarListen,
  Earth: Earth,
  EarthAfrica: EarthAfrica,
  EarthAmerica: EarthAmerica,
  EarthAmericas: EarthAmericas,
  EarthAsia: EarthAsia,
  EarthEurope: EarthEurope,
  EarthOceania: EarthOceania,
  Edit: Edit,
  EggFood: Egg,
  Eject: Eject,
  Elevator: Elevator,
  Ellipsis: Ellipsis,
  EllipsisH: EllipsisH,
  EllipsisV: EllipsisV,
  EllipsisVertical: EllipsisVertical,
  Envelope: Envelope,
  EnvelopeCircleCheck: EnvelopeCircleCheck,
  EnvelopeOpen: EnvelopeOpen,
  EnvelopeOpenText: EnvelopeOpenText,
  EnvelopeSquare: EnvelopeSquare,
  EnvelopesBulk: EnvelopesBulk,
  Equals: Equals,
  Eraser: Eraser,
  Ethernet: Ethernet,
  Eur: Eur,
  Eurosign: Euro,
  EuroSign: EuroSign,
  ExchangeSign: Exchange,
  ExchangeAlt: ExchangeAlt,
  Exclamation: Exclamation,
  ExclamationCircle: ExclamationCircle,
  ExclamationTriangle: ExclamationTriangle,
  Expand: Expand,
  ExpandAlt: ExpandAlt,
  ExpandArrowsAlt: ExpandArrowsAlt,
  Explosion: Explosion,
  ExternalLink: ExternalLink,
  ExternalLinkAlt: ExternalLinkAlt,
  ExternalLinkSquare: ExternalLinkSquare,
  ExternalLinkSquareAlt: ExternalLinkSquareAlt,
  Eye: Eye,
  EyeDropper: EyeDropper,
  EyeDropperEmpty: EyeDropperEmpty,
  EyeLowVision: EyeLowVision,
  EyeSlash: EyeSlash,
  Eyedropper: Eyedropper,
  //    // // // // f
  letterF: Fletter,
  FaceAngry: FaceAngry,
  FaceDizzy: FaceDizzy,
  FaceFlushed: FaceFlushed,
  FaceFrown: FaceFrown,
  FaceFrownOpen: FaceFrownOpen,
  FaceGrimace: FaceGrimace,
  FaceGrin: FaceGrin,
  FaceGrinBeam: FaceGrinBeam,
  FaceGrinBeamSweat: FaceGrinBeamSweat,
  FaceGrinHearts: FaceGrinHearts,
  FaceGrinSquint: FaceGrinSquint,
  FaceGrinSquintTears: FaceGrinSquintTears,
  FaceGrinStars: FaceGrinStars,
  FaceGrinTears: FaceGrinTears,
  FaceGrinTongue: FaceGrinTongue,
  FaceGrinTongueSquint: FaceGrinTongueSquint,
  FaceGrinTongueWink: FaceGrinTongueWink,
  FaceGrinWide: FaceGrinWide,
  FaceGrinWink: FaceGrinWink,
  FaceKiss: FaceKiss,
  FaceKissBeam: FaceKissBeam,
  FaceKissWinkHeart: FaceKissWinkHeart,
  FaceLaugh: FaceLaugh,
  FaceLaughBeam: FaceLaughBeam,
  FaceLaughSquint: FaceLaughSquint,
  FaceLaughWink: FaceLaughWink,
  FaceMeh: FaceMeh,
  FaceMehBlank: FaceMehBlank,
  FaceRollingEyes: FaceRollingEyes,
  FaceSadCry: FaceSadCry,
  FaceSadTear: FaceSadTear,
  FaceSmile: FaceSmile,
  FaceSmileBeam: FaceSmileBeam,
  FaceSmileWink: FaceSmileWink,
  FaceSurprise: FaceSurprise,
  FaceTired: FaceTired,
  Fan: Fan,
  FastBackward: FastBackward,
  FastForward: FastForward,
  Faucet: Faucet,
  FaucetDrip: FaucetDrip,
  Fax: Fax,
  Feather: Feather,
  FeatherAlt: FeatherAlt,
  FeatherPointed: FeatherPointed,
  FeedSymbol: Feed,
  Female: Female,
  Ferry: Ferry,
  FighterJet: FighterJet,
  File: File2,
  FileAlt: FileAlt,
  FileArchive: FileArchive,
  FileArrowDown: FileArrowDown,
  FileArrowUp: FileArrowUp,
  FileAudio: FileAudio,
  FileCircleCheck: FileCircleCheck,
  FileCircleExclamation: FileCircleExclamation,
  FileCircleMinus: FileCircleMinus,
  FileCirclePlus: FileCirclePlus,
  FileCircleQuestion: FileCircleQuestion,
  FileCircleXmark: FileCircleXmark,
  FileClipboard: FileClipboard,
  FileCode: FileCode,
  FileContract: FileContract,
  FileCsv: FileCsv,
  FileDownload: FileDownload,
  FileEdit: FileEdit,
  FileExcel: FileExcel,
  FileExport: FileExport,
  FileFragment: FileFragment,
  FileHalfDashed: FileHalfDashed,
  FileImage: FileImage,
  FileImport: FileImport,
  FileInvoice: FileInvoice,
  FileInvoiceDollar: FileInvoiceDollar,
  FileLines: FileLines,
  FileMedical: FileMedical,
  FileMedicalAlt: FileMedicalAlt,
  FilePdf: FilePdf,
  FilePen: FilePen,
  FilePowerpoint: FilePowerpoint,
  FilePrescription: FilePrescription,
  FileShield: FileShield,
  FileSignature: FileSignature,
  FileText: FileText,
  FileUpload: FileUpload,
  FileVideo: FileVideo,
  FileWaveform: FileWaveform,
  FileWord: FileWord,
  FileZipper: FileZipper,
  Fill: Fill,
  FillDrip: FillDrip,
  Film: Film,
  Filter: Filter,
  FilterCircleDollar: FilterCircleDollar,
  FilterCircleXmark: FilterCircleXmark,
  Fingerprint: Fingerprint,
  Fire: Fire,
  FireAlt: FireAlt,
  FireBurner: FireBurner,
  FireExtinguisher: FireExtinguisher,
  FireFlameCurved: FireFlameCurved,
  FireFlameSimple: FireFlameSimple,
  FirstAid: FirstAid,
  FishAnimal: Fish,
  FishFins: FishFins,
  FistRaised: FistRaised,
  Flag: Flag,
  FlagCheckered: FlagCheckered,
  FlagUsa: FlagUsa,
  Flask: Flask,
  FlaskVial: FlaskVial,
  FloppyDisk: FloppyDisk,
  FlorinSign: FlorinSign,
  Flushed: Flushed,
  Folder: Folder,
  FolderBlank: FolderBlank,
  FolderClosed: FolderClosed,
  FolderMinus: FolderMinus,
  FolderOpen: FolderOpen,
  FolderPlus: FolderPlus,
  FolderTree: FolderTree,
  Font: Font,
  FontAwesomeSymbol: FontAwesome,
  FontAwesomeFlag: FontAwesomeFlag,
  FontAwesomeLogoFullSymbol: FontAwesomeLogoFull,
  Football: Football,
  FootballBall: FootballBall,
  Forward: Forward,
  ForwardFast: ForwardFast,
  ForwardStep: ForwardStep,
  FrancSign: FrancSign,
  FrogAnimal: Frog,
  FrownFace: Frown,
  FrownOpenFace: FrownOpen,
  FunnelDollar: FunnelDollar,
  Futbolball: Futbol,
  FutbolBall: FutbolBall,
  letterG: Gletter,
  gamepad: Gamepad3,
  GasPump: GasPump,
  Gauge: Gauge,
  GaugeHigh: GaugeHigh,
  GaugeMed: GaugeMed,
  GaugeSimple: GaugeSimple,
  GaugeSimpleHigh: GaugeSimpleHigh,
  GaugeSimpleMed: GaugeSimpleMed,
  Gavel: Gavel,
  Gbp: Gbp,
  Gear: Gear,
  Gears: Gears,
  Gem: Gem,
  GenderlessSymbol: Genderless,
  Ghost: Ghost,
  Gift: Gift,
  Gifts: Gifts,
  GlassCheersFood: GlassCheers,
  GlassMartiniFood: GlassMartini,
  GlassMartiniAltFood: GlassMartiniAlt,
  GlassWater: GlassWater,
  GlassWaterDroplet: GlassWaterDroplet,
  GlassWhiskeyFood: GlassWhiskey,
  Glasses: Glasses,
  Globe: Globe,
  GlobeAfrica: GlobeAfrica,
  GlobeAmericas: GlobeAmericas,
  GlobeAsia: GlobeAsia,
  GlobeEurope: GlobeEurope,
  GlobeOceania: GlobeOceania,
  GolfBall: GolfBall,
  GolfBallTee: GolfBallTee,
  Gopuram: Gopuram,
  GraduationCap: GraduationCap,
  GreaterThan: GreaterThan,
  GreaterThanEqual: GreaterThanEqual,
  Grimace: Grimace,
  Grin: Grin,
  GrinAlt: GrinAlt,
  GrinBeam: GrinBeam,
  GrinBeamSweat: GrinBeamSweat,
  GrinHearts: GrinHearts,
  GrinSquint: GrinSquint,
  GrinSquintTears: GrinSquintTears,
  GrinStars: GrinStars,
  GrinTears: GrinTears,
  GrinTongue: GrinTongue,
  GrinTongueSquint: GrinTongueSquint,
  GrinTongueWink: GrinTongueWink,
  GrinWink: GrinWink,
  Grip: Grip,
  GripHorizontal: GripHorizontal,
  GripLines: GripLines,
  GripLinesVertical: GripLinesVertical,
  GripVertical: GripVertical,
  GroupArrowsRotate: GroupArrowsRotate,
  GuaraniSign: GuaraniSign,
  GuitarSymbol: Guitar,
  Gun: Gun,
  letterH: Hletter,
  HSquare: HSquare,
  HamburgerFood: Hamburger,
  Hammer: Hammer,
  Hamsa: Hamsa,
  Hand: Hand,
  HandBackFist: HandBackFist,
  HandDots: HandDots,
  HandFist: HandFist,
  HandHolding: HandHolding,
  HandHoldingDollar: HandHoldingDollar,
  HandHoldingDroplet: HandHoldingDroplet,
  HandHoldingHand: HandHoldingHand,
  HandHoldingHeart: HandHoldingHeart,
  HandHoldingMedical: HandHoldingMedical,
  HandHoldingUsd: HandHoldingUsd,
  HandHoldingWater: HandHoldingWater,
  HandLizard: HandLizard,
  HandMiddleFinger: HandMiddleFinger,
  HandPaper: HandPaper,
  HandPeace: HandPeace,
  HandPointDown: HandPointDown,
  HandPointLeft: HandPointLeft,
  HandPointRight: HandPointRight,
  HandPointUp: HandPointUp,
  HandPointer: HandPointer,
  HandRock: HandRock,
  HandScissors: HandScissors,
  HandSparkles: HandSparkles,
  HandSpock: HandSpock,
  Handcuffs: Handcuffs,
  Hands: Hands,
  HandsAmericanSignLanguageInterpreting: HandsAmericanSignLanguageInterpreting,
  HandsAslInterpreting: HandsAslInterpreting,
  HandsBound: HandsBound,
  HandsBubbles: HandsBubbles,
  HandsClapping: HandsClapping,
  HandsHelping: HandsHelping,
  HandsHolding: HandsHolding,
  HandsHoldingChild: HandsHoldingChild,
  HandsHoldingCircle: HandsHoldingCircle,
  HandsPraying: HandsPraying,
  HandsWash: HandsWash,
  Handshake: Handshake,
  HandshakeAlt: HandshakeAlt,
  HandshakeAltSlash: HandshakeAltSlash,
  HandshakeAngle: HandshakeAngle,
  HandshakeSimple: HandshakeSimple,
  HandshakeSimpleSlash: HandshakeSimpleSlash,
  HandshakeSlash: HandshakeSlash,
  HanukiahSymbol: Hanukiah,
  HardDrive: HardDrive,
  HardHat: HardHat,
  HardOfHearing: HardOfHearing,
  HashtagSign: Hashtag,
  HatCowboyCloth: HatCowboy,
  HatCowboySideCloth: HatCowboySide,
  HatHardCloth: HatHard,
  HatWizardMagic: HatWizard,
  Haykal: Haykal,
  Hdd: Hdd,
  HeadSideCough: HeadSideCough,
  HeadSideCoughSlash: HeadSideCoughSlash,
  HeadSideMask: HeadSideMask,
  HeadSideVirus: HeadSideVirus,
  Header: Header,
  Heading: Heading,
  Headphones: Headphones,
  HeadphonesAlt: HeadphonesAlt,
  HeadphonesSimple: HeadphonesSimple,
  Headset: Headset,
  Heart: Heart,
  HeartBroken: HeartBroken,
  HeartCircleBolt: HeartCircleBolt,
  HeartCircleCheck: HeartCircleCheck,
  HeartCircleExclamation: HeartCircleExclamation,
  HeartCircleMinus: HeartCircleMinus,
  HeartCirclePlus: HeartCirclePlus,
  HeartCircleXmark: HeartCircleXmark,
  HeartCrack: HeartCrack,
  HeartMusicCameraBolt: HeartMusicCameraBolt,
  HeartPulse: HeartPulse,
  Heartbeat: Heartbeat,
  Helicopter: Helicopter,
  HelicopterSymbol: HelicopterSymbol,
  HelmetSafety: HelmetSafety,
  HelmetUn: HelmetUn,
  HexagonNodes: HexagonNodes,
  HexagonNodesBolt: HexagonNodesBolt,
  Highlighter: Highlighter,
  Hiking: Hiking,
  HillAvalanche: HillAvalanche,
  HillRockslide: HillRockslide,
  HippoAnimal: Hippo,
  History: History2,
  HockeyPuckBall: HockeyPuck,
  HollyBerry: HollyBerry,
  Home: Home,
  HomeAlt: HomeAlt,
  HomeLg: HomeLg,
  HomeLgAlt: HomeLgAlt,
  HomeUser: HomeUser,
  HorseAAnimal: Horse,
  HorseHeadAnimal: HorseHead,
  Hospital: Hospital,
  HospitalAlt: HospitalAlt,
  HospitalSymbol: HospitalSymbol,
  HospitalUser: HospitalUser,
  HospitalWide: HospitalWide,
  HotTub: HotTub,
  HotTubPerson: HotTubPerson,
  Hotdog: Hotdog,
  Hotel: Hotel,
  Hourglass: Hourglass,
  Hourglass1: Hourglass1,
  Hourglass2: Hourglass2,
  Hourglass3: Hourglass3,
  HourglassEmpty: HourglassEmpty,
  HourglassEnd: HourglassEnd,
  HourglassHalf: HourglassHalf,
  HourglassStart: HourglassStart,
  House: House,
  HouseChimney: HouseChimney,
  HouseChimneyCrack: HouseChimneyCrack,
  HouseChimneyMedical: HouseChimneyMedical,
  HouseChimneyUser: HouseChimneyUser,
  HouseChimneyWindow: HouseChimneyWindow,
  HouseCircleCheck: HouseCircleCheck,
  HouseCircleExclamation: HouseCircleExclamation,
  HouseCircleXmark: HouseCircleXmark,
  HouseCrack: HouseCrack,
  HouseDamage: HouseDamage,
  HouseFire: HouseFire,
  HouseFlag: HouseFlag,
  HouseFloodWater: HouseFloodWater,
  HouseFloodWaterCircleArrowRight: HouseFloodWaterCircleArrowRight,
  HouseLaptop: HouseLaptop,
  HouseLock: HouseLock,
  HouseMedical: HouseMedical,
  HouseMedicalCircleCheck: HouseMedicalCircleCheck,
  HouseMedicalCircleExclamation: HouseMedicalCircleExclamation,
  HouseMedicalCircleXmark: HouseMedicalCircleXmark,
  HouseMedicalFlag: HouseMedicalFlag,
  HouseSignal: HouseSignal,
  HouseTsunami: HouseTsunami,
  HouseUser: HouseUser,
  Hryvnia: Hryvnia,
  HryvniaSign: HryvniaSign,
  Hurricane: Hurricane,
  letterI: Iletter,
  ICursor: ICursor,
  IceCream: IceCream,
  Icicles: Icicles,
  IconsSymbol: Icons,
  IdBadge: IdBadge,
  IdCard: IdCard,
  IdCardAlt: IdCardAlt,
  IdCardClip: IdCardClip,
  Igloo: Igloo,
  Ils: Ils,
  Image: Image2,
  ImagePortrait: ImagePortrait,
  Images: Images,
  Inbox: Inbox,
  Indent: Indent,
  IndianRupee: IndianRupee,
  IndianRupeeSign: IndianRupeeSign,
  Industry: Industry,
  Infinity2: Infinity2,
  Info: Info,
  InfoCircle: InfoCircle,
  Inr: Inr,
  Institution: Institution,
  Italic: Italic,
  Jar: Jar,
  JarWheat: JarWheat,
  JediSymbol: Jedi,
  JetFighter: JetFighter,
  JetFighterUp: JetFighterUp,
  Joint: Joint,
  JournalWhills: JournalWhills,
  Jpy: Jpy,
  JugDetergent: JugDetergent,
  letterK: Kletter,
  Kaaba: Kaaba,
  Key: Key,
  Keyboard: Keyboard,
  Khanda: Khanda,
  KipSign: KipSign,
  Kiss: Kiss,
  KissBeam: KissBeam,
  KissWinkHeart: KissWinkHeart,
  KitMedical: KitMedical,
  KitchenSet: KitchenSet,
  KiwiBirdAnimal: KiwiBird,
  Krw: Krw,
  letterL: Lletter,
  LadderWater: LadderWater,
  LandMineOn: LandMineOn,
  Landmark: Landmark,
  LandmarkAlt: LandmarkAlt,
  LandmarkDome: LandmarkDome,
  LandmarkFlag: LandmarkFlag,
  Language: Language,
  Laptop: Laptop,
  LaptopCode: LaptopCode,
  LaptopFile: LaptopFile,
  LaptopHouse: LaptopHouse,
  LaptopMedical: LaptopMedical,
  LariSign: LariSign,
  LaughFace: Laugh,
  LaughBeamFace: LaughBeam,
  LaughSquintFace: LaughSquint,
  LaughWinkFace: LaughWink,
  LayerGroup: LayerGroup,
  Leaf: Leaf,
  LeftLong: LeftLong,
  LeftRight: LeftRight,
  Legal: Legal,
  LemonFood: Lemon,
  LessThan: LessThan,
  LessThanEqual: LessThanEqual,
  LevelDown: LevelDown,
  LevelDownAlt: LevelDownAlt,
  LevelUp: LevelUp,
  LevelUpAlt: LevelUpAlt,
  LifeRing: LifeRing,
  Lightbulb: Lightbulb,
  LineChart: LineChart,
  LinesLeaning: LinesLeaning,
  LinkSymbol: Link,
  LinkSlash: LinkSlash,
  LiraSign: LiraSign,
  List: List,
  List12: List12,
  ListAlt: ListAlt,
  ListCheck: ListCheck,
  ListDots: ListDots,
  ListNumeric: ListNumeric,
  ListOl: ListOl,
  ListSquares: ListSquares,
  ListUl: ListUl,
  LitecoinSign: LitecoinSign,
  Location: Location2,
  LocationArrow: LocationArrow,
  LocationCrosshairs: LocationCrosshairs,
  LocationDot: LocationDot,
  LocationPin: LocationPin,
  LocationPinLock: LocationPinLock,
  Lock: Lock3,
  LockOpen: LockOpen,
  Locust: Locust,
  LongArrowAltDown: LongArrowAltDown,
  LongArrowAltLeft: LongArrowAltLeft,
  LongArrowAltRight: LongArrowAltRight,
  LongArrowAltUp: LongArrowAltUp,
  LongArrowDown: LongArrowDown,
  LongArrowLeft: LongArrowLeft,
  LongArrowRight: LongArrowRight,
  LongArrowUp: LongArrowUp,
  LowVision: LowVision,
  LuggageCart: LuggageCart,
  Lungs: Lungs,
  LungsVirus: LungsVirus,
  letterM: Mletter,
  Magic: Magic,
  MagicWandSparkles: MagicWandSparkles,
  Magnet: Magnet,
  MagnifyingGlass: MagnifyingGlass,
  MagnifyingGlassArrowRight: MagnifyingGlassArrowRight,
  MagnifyingGlassChart: MagnifyingGlassChart,
  MagnifyingGlassDollar: MagnifyingGlassDollar,
  MagnifyingGlassLocation: MagnifyingGlassLocation,
  MagnifyingGlassMinus: MagnifyingGlassMinus,
  MagnifyingGlassPlus: MagnifyingGlassPlus,
  MailBulk: MailBulk,
  MailForward: MailForward,
  MailReply: MailReply,
  MailReplyAll: MailReplyAll,
  Male: Male,
  ManatSign: ManatSign,
  Map: Map2,
  MapLocation: MapLocation,
  MapLocationDot: MapLocationDot,
  MapMarked: MapMarked,
  MapMarkedAlt: MapMarkedAlt,
  MapMarker: MapMarker,
  MapMarkerAlt: MapMarkerAlt,
  MapPin: MapPin,
  MapSigns: MapSigns,
  Marker: Marker,
  Mars: Mars,
  MarsAndVenus: MarsAndVenus,
  MarsAndVenusBurst: MarsAndVenusBurst,
  MarsDouble: MarsDouble,
  MarsStroke: MarsStroke,
  MarsStrokeH: MarsStrokeH,
  MarsStrokeRight: MarsStrokeRight,
  MarsStrokeUp: MarsStrokeUp,
  MarsStrokeV: MarsStrokeV,
  MartiniGlass: MartiniGlass,
  MartiniGlassCitrus: MartiniGlassCitrus,
  MartiniGlassEmpty: MartiniGlassEmpty,
  Mask: Mask,
  MaskFace: MaskFace,
  MaskVentilator: MaskVentilator,
  MasksTheater: MasksTheater,
  MattressPillow: MattressPillow,
  Maximize: Maximize,
  Medal: Medal,
  Medkit: Medkit,
  MehFace: Meh,
  MehBlank: MehBlank,
  MehRollingEyes: MehRollingEyes,
  Memory: Memory,
  Menorah: Menorah,
  Mercury: Mercury,
  Message: Message,
  Meteor: Meteor,
  Microchip: Microchip,
  Microphone: Microphone,
  MicrophoneAlt: MicrophoneAlt,
  MicrophoneAltSlash: MicrophoneAltSlash,
  MicrophoneLines: MicrophoneLines,
  MicrophoneLinesSlash: MicrophoneLinesSlash,
  MicrophoneSlash: MicrophoneSlash,
  Microscope: Microscope,
  MillSign: MillSign,
  Minimize: Minimize,
  Minus: Minus,
  MinusCircle: MinusCircle,
  MinusSquare: MinusSquare,
  Mitten: Mitten,
  Mobile: Mobile,
  MobileAlt: MobileAlt,
  MobileAndroid: MobileAndroid,
  MobileAndroidAlt: MobileAndroidAlt,
  MobileButton: MobileButton,
  MobilePhone: MobilePhone,
  MobileRetro: MobileRetro,
  MobileScreen: MobileScreen,
  MobileScreenButton: MobileScreenButton,
  MoneyBill: MoneyBill,
  MoneyBill1: MoneyBill1,
  MoneyBill1Wave: MoneyBill1Wave,
  MoneyBillAlt: MoneyBillAlt,
  MoneyBillTransfer: MoneyBillTransfer,
  MoneyBillTrendUp: MoneyBillTrendUp,
  MoneyBillWave: MoneyBillWave,
  MoneyBillWaveAlt: MoneyBillWaveAlt,
  MoneyBillWheat: MoneyBillWheat,
  MoneyBills: MoneyBills,
  MoneyCheck: MoneyCheck,
  MoneyCheckAlt: MoneyCheckAlt,
  MoneyCheckDollar: MoneyCheckDollar,
  Monument: Monument,
  MoonWeather: Moon,
  MortarBoard: MortarBoard,
  MortarPestle: MortarPestle,
  Mosque: Mosque,
  MosquitoAnimal: Mosquito,
  MosquitoNet: MosquitoNet,
  Motorcycle: Motorcycle,
  Mound: Mound,
  Mountain: Mountain,
  MountainCity: MountainCity,
  MountainSun: MountainSun,
  Mouse: Mouse,
  MousePointer: MousePointer,
  MugHot: MugHot,
  MugSaucer: MugSaucer,
  Multiply: Multiply,
  Museum: Museum,
  Music: Music,
  letterN: Nletter,
  NairaSign: NairaSign,
  Navicon: Navicon,
  NetworkWired: NetworkWired,
  Neuter: Neuter,
  Newspaper: Newspaper,
  NotEqual: NotEqual,
  Notdef: Notdef,
  NoteSticky: NoteSticky,
  NotesMedical: NotesMedical,
  letterO: Oletter,
  ObjectGroup: ObjectGroup,
  ObjectUngroup: ObjectUngroup,
  OilCan: OilCan,
  OilWell: OilWell,
  Om: Om,
  Animal: Otter,
  Outdent: Outdent,
  letterP: Pletter,
  Pager: Pager,
  PaintBrush: PaintBrush,
  PaintRoller: PaintRoller,
  Paintbrush: Paintbrush,
  Palette: Palette,
  Pallet: Pallet,
  Panorama: Panorama,
  PaperPlane: PaperPlane,
  Paperclip: Paperclip,
  ParachuteBox: ParachuteBox,
  Paragraph: Paragraph,
  Parking: Parking,
  Passport: Passport,
  Pastafarianism: Pastafarianism,
  Paste: Paste,
  Pause: Pause,
  PauseCircle: PauseCircle,
  PawAnimal: Paw,
  Peace: Peace,
  Pen: Pen,
  PenAlt: PenAlt,
  PenClip: PenClip,
  PenFancy: PenFancy,
  PenNib: PenNib,
  PenRuler: PenRuler,
  PenSquare: PenSquare,
  PenToSquare: PenToSquare,
  Pencil: Pencil,
  PencilAlt: PencilAlt,
  PencilRuler: PencilRuler,
  PencilSquare: PencilSquare,
  PeopleArrows: PeopleArrows,
  PeopleArrowsLeftRight: PeopleArrowsLeftRight,
  PeopleCarry: PeopleCarry,
  PeopleCarryBox: PeopleCarryBox,
  PeopleGroup: PeopleGroup,
  PeopleLine: PeopleLine,
  PeoplePulling: PeoplePulling,
  PeopleRobbery: PeopleRobbery,
  PeopleRoof: PeopleRoof,
  PepperHot: PepperHot,
  Percent: Percent,
  Percentage: Percentage,
  Person: Person,
  PersonArrowDownToLine: PersonArrowDownToLine,
  PersonArrowUpFromLine: PersonArrowUpFromLine,
  PersonBiking: PersonBiking,
  PersonBooth: PersonBooth,
  PersonBreastfeeding: PersonBreastfeeding,
  PersonBurst: PersonBurst,
  PersonCane: PersonCane,
  PersonChalkboard: PersonChalkboard,
  PersonCircleCheck: PersonCircleCheck,
  PersonCircleExclamation: PersonCircleExclamation,
  PersonCircleMinus: PersonCircleMinus,
  PersonCirclePlus: PersonCirclePlus,
  PersonCircleQuestion: PersonCircleQuestion,
  PersonCircleXmark: PersonCircleXmark,
  PersonDigging: PersonDigging,
  PersonDotsFromLine: PersonDotsFromLine,
  PersonDress: PersonDress,
  PersonDressBurst: PersonDressBurst,
  PersonDrowning: PersonDrowning,
  PersonFalling: PersonFalling,
  PersonFallingBurst: PersonFallingBurst,
  PersonHalfDress: PersonHalfDress,
  PersonHarassing: PersonHarassing,
  PersonHiking: PersonHiking,
  PersonMilitaryPointing: PersonMilitaryPointing,
  PersonMilitaryRifle: PersonMilitaryRifle,
  PersonMilitaryToPerson: PersonMilitaryToPerson,
  PersonPraying: PersonPraying,
  PersonPregnant: PersonPregnant,
  PersonRays: PersonRays,
  PersonRifle: PersonRifle,
  PersonRunning: PersonRunning,
  PersonShelter: PersonShelter,
  PersonSkating: PersonSkating,
  PersonSkiing: PersonSkiing,
  PersonSkiingNordic: PersonSkiingNordic,
  PersonSnowboarding: PersonSnowboarding,
  PersonSwimming: PersonSwimming,
  PersonThroughWindow: PersonThroughWindow,
  PersonWalking: PersonWalking,
  PersonWalkingArrowLoopLeft: PersonWalkingArrowLoopLeft,
  PersonWalkingArrowRight: PersonWalkingArrowRight,
  PersonWalkingDashedLineArrowRight: PersonWalkingDashedLineArrowRight,
  PersonWalkingLuggage: PersonWalkingLuggage,
  PersonWalkingWithCane: PersonWalkingWithCane,
  PesetaSign: PesetaSign,
  PesoSign: PesoSign,
  Phone: Phone,
  PhoneAlt: PhoneAlt,
  PhoneFlip: PhoneFlip,
  PhoneSlash: PhoneSlash,
  PhoneSquare: PhoneSquare,
  PhoneSquareAlt: PhoneSquareAlt,
  PhoneVolume: PhoneVolume,
  PhotoFilm: PhotoFilm,
  PhotoVideo: PhotoVideo,
  PieChart: PieChart2,
  PiggyBank: PiggyBank2,
  Pills: Pills,
  PingPongPaddleBall: PingPongPaddleBall,
  PizzaSlice: PizzaSlice,
  PlaceOfWorship: PlaceOfWorship,
  Plane: Plane2,
  PlaneArrival: PlaneArrival,
  PlaneCircleCheck: PlaneCircleCheck,
  PlaneCircleExclamation: PlaneCircleExclamation,
  PlaneCircleXmark: PlaneCircleXmark,
  PlaneDeparture: PlaneDeparture,
  PlaneLock: PlaneLock,
  PlaneSlash: PlaneSlash,
  PlaneUp: PlaneUp,
  PlantWilt: PlantWilt,
  PlateWheat: PlateWheat,
  Play: Play2,
  PlayCircle: PlayCircle2,
  Plug: Plug2,
  PlugCircleBolt: PlugCircleBolt,
  PlugCircleCheck: PlugCircleCheck,
  PlugCircleExclamation: PlugCircleExclamation,
  PlugCircleMinus: PlugCircleMinus,
  PlugCirclePlus: PlugCirclePlus,
  PlugCircleXmark: PlugCircleXmark,
  Plus: Plus2,
  PlusCircle: PlusCircle2,
  PlusMinus: PlusMinus,
  PlusSquare: PlusSquare2,
  Podcast: Podcast2,
  Poll: Poll,
  PollH: PollH,
  Poo: Poo,
  PooBolt: PooBolt,
  PooStorm: PooStorm,
  Poop: Poop,
  Portrait: Portrait,
  PoundSign: PoundSign,
  PowerOff: PowerOff,
  Pray: Pray,
  PrayingHands: PrayingHands,
  Prescription: Prescription,
  PrescriptionBottle: PrescriptionBottle,
  PrescriptionBottleAlt: PrescriptionBottleAlt,
  PrescriptionBottleMedical: PrescriptionBottleMedical,
  Print: Print,
  Procedures: Procedures,
  ProjectDiagram: ProjectDiagram,
  PumpMedical: PumpMedical,
  PumpSoap: PumpSoap,
  PuzzlePiece: PuzzlePiece,
  letterQ: Qletter,
  Qrcode: Qrcode,
  Question: Question,
  QuestionCircle: QuestionCircle,
  QuidditchMagic: Quidditch,
  QuidditchBroomBall: QuidditchBroomBall,
  QuoteLeft: QuoteLeft,
  QuoteLeftAlt: QuoteLeftAlt,
  QuoteRight: QuoteRight,
  QuoteRightAlt: QuoteRightAlt,
  QuranSymbol: Quran,
  letterR: Rletter,
  RadiationSynbol: Radiation,
  RadiationAlt: RadiationAlt,
  RadioMusic: Radio,
  RainbowWeather: Rainbow,
  Random: Random,
  RankingStar: RankingStar,
  Receipt: Receipt,
  RecordVinyl: RecordVinyl,
  RectangleAd: RectangleAd,
  RectangleList: RectangleList,
  RectangleTimes: RectangleTimes,
  RectangleXmark: RectangleXmark,
  Recycle: Recycle,
  Redo: Redo,
  RedoAlt: RedoAlt,
  Refresh: Refresh,
  Registered: Registered,
  Remove: Remove,
  RemoveFormat: RemoveFormat,
  Reorder: Reorder,
  Repeat: Repeat,
  Reply: Reply,
  ReplyAll: ReplyAll,
  Republican: Republican,
  Restroom: Restroom,
  Retweet: Retweet,
  RibbonSymbol: Ribbon,
  RightFromBracket: RightFromBracket,
  RightLeft: RightLeft,
  RightLong: RightLong,
  RightToBracket: RightToBracket,
  Ring: Ring,
  Rmb: Rmb,
  Road: Road,
  RoadBarrier: RoadBarrier,
  RoadBridge: RoadBridge,
  RoadCircleCheck: RoadCircleCheck,
  RoadCircleExclamation: RoadCircleExclamation,
  RoadCircleXmark: RoadCircleXmark,
  RoadLock: RoadLock,
  RoadSpikes: RoadSpikes,
  Robot: Robot,
  Rocket: Rocket,
  RodAsclepius: RodAsclepius,
  RodSnake: RodSnake,
  Rotate: Rotate,
  RotateBack: RotateBack,
  RotateBackward: RotateBackward,
  RotateForward: RotateForward,
  RotateLeft: RotateLeft,
  RotateRight: RotateRight,
  Rouble: Rouble,
  Route: Route,
  Rss: Rss,
  RssSquare: RssSquare,
  Rub: Rub,
  Ruble: Ruble,
  RubleSign: RubleSign,
  Rug: Rug,
  Ruler: Ruler,
  RulerCombined: RulerCombined,
  RulerHorizontal: RulerHorizontal,
  RulerVertical: RulerVertical,
  Running: Running,
  Rupee: Rupee,
  RupeeSign: RupeeSign,
  RupiahSign: RupiahSign,
  letterS: Sletter,
  SackDollar: SackDollar,
  SackXmark: SackXmark,
  SadCry: SadCry,
  SadTear: SadTear,
  Sailboat: Sailboat,
  Satellite: Satellite,
  SatelliteDish: SatelliteDish,
  Save: Save,
  ScaleBalanced: ScaleBalanced,
  ScaleUnbalanced: ScaleUnbalanced,
  ScaleUnbalancedFlip: ScaleUnbalancedFlip,
  School: School,
  SchoolCircleCheck: SchoolCircleCheck,
  SchoolCircleExclamation: SchoolCircleExclamation,
  SchoolCircleXmark: SchoolCircleXmark,
  SchoolFlag: SchoolFlag,
  SchoolLock: SchoolLock,
  Scissors: Scissors,
  Screwdriver: Screwdriver,
  ScrewdriverWrench: ScrewdriverWrench,
  Scroll: Scroll,
  ScrollTorah: ScrollTorah,
  SdCard: SdCard,
  Search: Search,
  SearchDollar: SearchDollar,
  SearchLocation: SearchLocation,
  SearchMinus: SearchMinus,
  SearchPlus: SearchPlus,
  Section: Section,
  Seedling: Seedling,
  Server: Server,
  Shapes: Shapes,
  Share: Share,
  ShareAlt: ShareAlt,
  ShareAltSquare: ShareAltSquare,
  ShareFromSquare: ShareFromSquare,
  ShareNodes: ShareNodes,
  ShareSquare: ShareSquare,
  SheetPlastic: SheetPlastic,
  Shekel: Shekel,
  ShekelSign: ShekelSign,
  Sheqel: Sheqel,
  SheqelSign: SheqelSign,
  Shield: Shield,
  ShieldAlt: ShieldAlt,
  ShieldBlank: ShieldBlank,
  ShieldCat: ShieldCat,
  ShieldDog: ShieldDog,
  ShieldHalved: ShieldHalved,
  ShieldHeart: ShieldHeart,
  ShieldVirus: ShieldVirus,
  Ship: Ship,
  ShippingFast: ShippingFast,
  Shirt: Shirt,
  ShoePrints: ShoePrints,
  Shop: Shop,
  ShopLock: ShopLock,
  ShopSlash: ShopSlash,
  ShoppingBag: ShoppingBag,
  ShoppingBasket: ShoppingBasket,
  ShoppingCart: ShoppingCart,
  Shower: Shower,
  ShrimpFood: Shrimp,
  Shuffle: Shuffle,
  ShuttleSpace: ShuttleSpace,
  ShuttleVan: ShuttleVan,
  Sign: Sign,
  SignHanging: SignHanging,
  SignIn: SignIn,
  SignInAlt: SignInAlt,
  SignLanguage: SignLanguage,
  SignOut: SignOut,
  SignOutAlt: SignOutAlt,
  Signal: Signal,
  Signal5: Signal5,
  SignalPerfect: SignalPerfect,
  Signature: Signature,
  Signing: Signing,
  SignsPost: SignsPost,
  SimCard: SimCard,
  Sink: Sink,
  Sitemap: Sitemap,
  Skating: Skating,
  Skiing: Skiing,
  SkiingNordic: SkiingNordic,
  Skull: Skull,
  SkullCrossbones: SkullCrossbones,
  Slash: Slash,
  Sleigh: Sleigh,
  Sliders: Sliders,
  SlidersH: SlidersH,
  SmileFace: Smile,
  SmileBeam: SmileBeam,
  SmileWink: SmileWink,
  Smog: Smog,
  Smoking: Smoking,
  SmokingBan: SmokingBan,
  Sms: Sms,
  Snowboarding: Snowboarding,
  SnowflakeWeather: Snowflake,
  SnowmanWeather: Snowman,
  Snowplow: Snowplow,
  Soap: Soap,
  SoccerBall: SoccerBall,
  Socks: Socks,
  SolarPanel: SolarPanel,
  Sort: Sort,
  SortAlphaAsc: SortAlphaAsc,
  SortAlphaDesc: SortAlphaDesc,
  SortAlphaDown: SortAlphaDown,
  SortAlphaDownAlt: SortAlphaDownAlt,
  SortAlphaUp: SortAlphaUp,
  SortAlphaUpAlt: SortAlphaUpAlt,
  SortAmountAsc: SortAmountAsc,
  SortAmountDesc: SortAmountDesc,
  SortAmountDown: SortAmountDown,
  SortAmountDownAlt: SortAmountDownAlt,
  SortAmountUp: SortAmountUp,
  SortAmountUpAlt: SortAmountUpAlt,
  SortAsc: SortAsc,
  SortDesc: SortDesc,
  SortDown: SortDown,
  SortNumericAsc: SortNumericAsc,
  SortNumericDesc: SortNumericDesc,
  SortNumericDown: SortNumericDown,
  SortNumericDownAlt: SortNumericDownAlt,
  SortNumericUp: SortNumericUp,
  SortNumericUpAlt: SortNumericUpAlt,
  SortUp: SortUp,
  Spa: Spa,
  SpaceShuttle: SpaceShuttle,
  SpaghettiMonsterFlying: SpaghettiMonsterFlying,
  SpellCheck: SpellCheck,
  Spider: Spider,
  Spinner: Spinner,
  Splotch: Splotch,
  SpoonFood: Spoon,
  SprayCan: SprayCan,
  SprayCanSparkles: SprayCanSparkles,
  Sprout: Sprout,
  Square: Square,
  SquareArrowUpRight: SquareArrowUpRight,
  SquareBinary: SquareBinary,
  SquareCaretDown: SquareCaretDown,
  SquareCaretLeft: SquareCaretLeft,
  SquareCaretRight: SquareCaretRight,
  SquareCaretUp: SquareCaretUp,
  SquareCheck: SquareCheck,
  SquareEnvelope: SquareEnvelope,
  SquareFull: SquareFull,
  SquareH: SquareH,
  SquareMinus: SquareMinus,
  SquareNfi: SquareNfi,
  SquareParking: SquareParking,
  SquarePen: SquarePen,
  SquarePersonConfined: SquarePersonConfined,
  SquarePhone: SquarePhone,
  SquarePhoneFlip: SquarePhoneFlip,
  SquarePlus: SquarePlus,
  SquarePollHorizontal: SquarePollHorizontal,
  SquarePollVertical: SquarePollVertical,
  SquareRootAlt: SquareRootAlt,
  SquareRootVariable: SquareRootVariable,
  SquareRss: SquareRss,
  SquareShareNodes: SquareShareNodes,
  SquareUpRight: SquareUpRight,
  SquareVirus: SquareVirus,
  SquareXmark: SquareXmark,
  StaffAesculapius: StaffAesculapius,
  StaffSnake: StaffSnake,
  Stairs: Stairs,
  Stamp: Stamp,
  Stapler: Stapler,
  Star: Star,
  StarAndCrescentSymbol: StarAndCrescent,
  StarHalf: StarHalf,
  StarHalfAlt: StarHalfAlt,
  StarHalfStroke: StarHalfStroke,
  StarOfDavidSymbol: StarOfDavid,
  StarOfLifeSymbol: StarOfLife,
  StepBackward: StepBackward,
  StepForward: StepForward,
  SterlingSign: SterlingSign,
  Stethoscope: Stethoscope,
  StickyNote: StickyNote,
  Stop: Stop,
  StopCircle: StopCircle,
  Stopwatch: Stopwatch,
  Stopwatch20: Stopwatch20,
  Store: Store,
  StoreAlt: StoreAlt,
  StoreAltSlash: StoreAltSlash,
  StoreSlash: StoreSlash,
  Stream: Stream,
  StreetView: StreetView,
  Strikethrough: Strikethrough,
  Stroopwafel: Stroopwafel,
  Subscript: Subscript,
  Subtract: Subtract,
  Subway: Subway,
  Suitcase: Suitcase,
  SuitcaseMedical: SuitcaseMedical,
  SuitcaseRolling: SuitcaseRolling,
  SunWeather: Sun,
  SunPlantWilt: SunPlantWilt,
  Superscript: Superscript,
  Surprise: Surprise,
  Swatchbook: Swatchbook,
  Swimmer: Swimmer,
  SwimmingPool: SwimmingPool,
  Synagogue: Synagogue,
  Sync: Sync,
  SyncAlt: SyncAlt,
  Syringe: Syringe,
  letterT: Tletter,
  TShirt: TShirt,
  Table: Table,
  TableCells: TableCells,
  TableCellsColumnLock: TableCellsColumnLock,
  TableCellsLarge: TableCellsLarge,
  TableCellsRowLock: TableCellsRowLock,
  TableCellsRowUnlock: TableCellsRowUnlock,
  TableColumns: TableColumns,
  TableList: TableList,
  TableTennis: TableTennis,
  TableTennisPaddleBall: TableTennisPaddleBall,
  Tablet: Tablet,
  TabletAlt: TabletAlt,
  TabletAndroid: TabletAndroid,
  TabletButton: TabletButton,
  TabletScreenButton: TabletScreenButton,
  Tablets: Tablets,
  TachographDigital: TachographDigital,
  Tachometer: Tachometer,
  TachometerAlt: TachometerAlt,
  TachometerAltAverage: TachometerAltAverage,
  TachometerAltFast: TachometerAltFast,
  TachometerAverage: TachometerAverage,
  TachometerFast: TachometerFast,
  Tag: Tag,
  Tags: Tags,
  Tanakh: Tanakh,
  Tape: Tape,
  Tarp: Tarp,
  TarpDroplet: TarpDroplet,
  Tasks: Tasks,
  TasksAlt: TasksAlt,
  TaxiCar: Taxi,
  Teeth: Teeth,
  TeethOpen: TeethOpen,
  Teletype: Teletype,
  Television: Television,
  Temperature0: Temperature0,
  Temperature1: Temperature1,
  Temperature2: Temperature2,
  Temperature3: Temperature3,
  Temperature4: Temperature4,
  TemperatureArrowDown: TemperatureArrowDown,
  TemperatureArrowUp: TemperatureArrowUp,
  TemperatureDown: TemperatureDown,
  TemperatureEmpty: TemperatureEmpty,
  TemperatureFull: TemperatureFull,
  TemperatureHalf: TemperatureHalf,
  TemperatureHigh: TemperatureHigh,
  TemperatureLow: TemperatureLow,
  TemperatureQuarter: TemperatureQuarter,
  TemperatureThreeQuarters: TemperatureThreeQuarters,
  TemperatureUp: TemperatureUp,
  Tenge: Tenge,
  TengeSign: TengeSign,
  Tent: Tent,
  TentArrowDownToLine: TentArrowDownToLine,
  TentArrowLeftRight: TentArrowLeftRight,
  TentArrowTurnLeft: TentArrowTurnLeft,
  TentArrowsDown: TentArrowsDown,
  Tents: Tents,
  Terminal: Terminal,
  TextHeight: TextHeight,
  TextSlash: TextSlash,
  TextWidth: TextWidth,
  Th: Th,
  ThLarge: ThLarge,
  ThList: ThList,
  TheaterMasks: TheaterMasks,
  Thermometer: Thermometer,
  Thermometer0: Thermometer0,
  Thermometer1: Thermometer1,
  Thermometer2: Thermometer2,
  Thermometer3: Thermometer3,
  Thermometer4: Thermometer4,
  ThermometerEmpty: ThermometerEmpty,
  ThermometerFull: ThermometerFull,
  ThermometerHalf: ThermometerHalf,
  ThermometerQuarter: ThermometerQuarter,
  ThermometerThreeQuarters: ThermometerThreeQuarters,
  ThumbTack: ThumbTack,
  ThumbTackSlash: ThumbTackSlash,
  ThumbsDown: ThumbsDown,
  ThumbsUp: ThumbsUp,
  Thunderstorm: Thunderstorm,
  Ticket: Ticket,
  TicketAlt: TicketAlt,
  TicketSimple: TicketSimple,
  Timeline: Timeline,
  Times: Times,
  TimesCircle: TimesCircle,
  TimesRectangle: TimesRectangle,
  TimesSquare: TimesSquare,
  Tint: Tint,
  TintSlash: TintSlash,
  Tired: Tired,
  ToggleOff: ToggleOff,
  ToggleOn: ToggleOn,
  Toilet: Toilet,
  ToiletPaper: ToiletPaper,
  ToiletPaperSlash: ToiletPaperSlash,
  ToiletPortable: ToiletPortable,
  ToiletsPortable: ToiletsPortable,
  Toolbox: Toolbox,
  Tools: Tools,
  Tooth: Tooth,
  TorahSymbolBook: Torah,
  ToriiGate: ToriiGate,
  Tornado: Tornado,
  TowerBroadcast: TowerBroadcast,
  TowerCell: TowerCell,
  TowerObservation: TowerObservation,
  Tractor: Tractor,
  Trademark: Trademark,
  TrafficLight: TrafficLight,
  Trailer: Trailer,
  Train: Train,
  TrainSubway: TrainSubway,
  TrainTram: TrainTram,
  Tram: Tram,
  Transgender: Transgender,
  TransgenderAlt: TransgenderAlt,
  Trash: Trash,
  TrashAlt: TrashAlt,
  TrashArrowUp: TrashArrowUp,
  TrashCan: TrashCan,
  TrashCanArrowUp: TrashCanArrowUp,
  TrashRestore: TrashRestore,
  TrashRestoreAlt: TrashRestoreAlt,
  Tree: Tree,
  TreeCity: TreeCity,
  TriangleCircleSquare: TriangleCircleSquare,
  TriangleExclamation: TriangleExclamation,
  Trophy: Trophy2,
  Trowel: Trowel,
  TrowelBricks: TrowelBricks,
  Truck: Truck2,
  TruckArrowRight: TruckArrowRight,
  TruckDroplet: TruckDroplet,
  TruckFast: TruckFast,
  TruckField: TruckField,
  TruckFieldUn: TruckFieldUn,
  TruckFront: TruckFront,
  TruckLoading: TruckLoading,
  TruckMedical: TruckMedical,
  TruckMonster: TruckMonster,
  TruckMoving: TruckMoving,
  TruckPickup: TruckPickup,
  TruckPlane: TruckPlane,
  TruckRampBox: TruckRampBox,
  Try: Try,
  Tshirt: Tshirt,
  Tty: Tty,
  TurkishLira: TurkishLira,
  TurkishLiraSign: TurkishLiraSign,
  TurnDown: TurnDown,
  TurnUp: TurnUp,
  Tv: Tv2,
  TvAlt: TvAlt,
  letterU: Uletter,
  Umbrella: Umbrella,
  UmbrellaBeach: UmbrellaBeach,
  Underline: Underline,
  Undo: Undo,
  UndoAlt: UndoAlt,
  UniversalAccess: UniversalAccess,
  University: University,
  Unlink: Unlink,
  Unlock: Unlock,
  UnlockAlt: UnlockAlt,
  UnlockKeyhole: UnlockKeyhole,
  Unsorted: Unsorted,
  UpDown: UpDown,
  UpDownLeftRight: UpDownLeftRight,
  UpLong: UpLong,
  UpRightAndDownLeftFromCenter: UpRightAndDownLeftFromCenter,
  UpRightFromSquare: UpRightFromSquare,
  Upload: Upload,
  Usd: Usd,
  User: User,
  UserAlt: UserAlt,
  UserAltSlash: UserAltSlash,
  UserAstronaut: UserAstronaut,
  UserCheck: UserCheck,
  UserCircle: UserCircle,
  UserClock: UserClock,
  UserCog: UserCog,
  UserDoctor: UserDoctor,
  UserEdit: UserEdit,
  UserFriends: UserFriends,
  UserGear: UserGear,
  UserGraduate: UserGraduate,
  UserGroup: UserGroup,
  UserInjured: UserInjured,
  UserLarge: UserLarge,
  UserLargeSlash: UserLargeSlash,
  UserLock: UserLock,
  UserMd: UserMd,
  UserMinus: UserMinus,
  UserNinja: UserNinja,
  UserNurse: UserNurse,
  UserPen: UserPen,
  UserPlus: UserPlus,
  UserSecret: UserSecret,
  UserShield: UserShield,
  UserSlash: UserSlash,
  UserTag: UserTag,
  UserTie: UserTie,
  UserTimes: UserTimes,
  UserXmark: UserXmark,
  Users: Users,
  UsersBetweenLines: UsersBetweenLines,
  UsersCog: UsersCog,
  UsersGear: UsersGear,
  UsersLine: UsersLine,
  UsersRays: UsersRays,
  UsersRectangle: UsersRectangle,
  UsersSlash: UsersSlash,
  UsersViewfinder: UsersViewfinder,
  UtensilSpoon: UtensilSpoon,
  Utensils: Utensils,
  letterV: Vletter,
  VanShuttle: VanShuttle,
  Vault: Vault,
  Vcard: Vcard,
  VectorSquare: VectorSquare,
  Venus: Venus,
  VenusDouble: VenusDouble,
  VenusMars: VenusMars,
  Vest: Vest,
  VestPatches: VestPatches,
  Vial: Vial,
  VialCircleCheck: VialCircleCheck,
  VialVirus: VialVirus,
  Vials: Vials,
  Video: Video,
  VideoCamera: VideoCamera,
  VideoSlash: VideoSlash,
  Vihara: Vihara,
  Virus: Virus,
  VirusCovidSymbol: VirusCovid,
  VirusCovidSlash: VirusCovidSlash,
  VirusSlash: VirusSlash,
  Viruses: Viruses,
  Voicemail: Voicemail,
  Volcano: Volcano,
  Volleyball: Volleyball,
  VolleyballBall: VolleyballBall,
  VolumeControlPhone: VolumeControlPhone,
  VolumeDownMusic: VolumeDown,
  VolumeHighMusic: VolumeHigh,
  VolumeLowMusic: VolumeLow,
  VolumeMuteMusic: VolumeMute,
  VolumeOffMusic: VolumeOff,
  VolumeTimesMusic: VolumeTimes,
  VolumeUpMusic: VolumeUp,
  VolumeXmarkMusic: VolumeXmark,
  VoteYea: VoteYea,
  VrCardboard: VrCardboard,
  letterW: Wletter,
  WalkieTalkie: WalkieTalkie,
  Walking: Walking,
  Wallet: Wallet,
  Warehouse: Warehouse,
  Warning: Warning,
  WaterFood: Water,
  WaterLadder: WaterLadder,
  WaveSquare: WaveSquare,
  WebAwesome: WebAwesome,
  Weight: Weight,
  WeightHanging: WeightHanging,
  WeightScale: WeightScale,
  WheatAlt: WheatAlt,
  WheatAwn: WheatAwn,
  WheatAwnCircleExclamation: WheatAwnCircleExclamation,
  Wheelchair: Wheelchair,
  WheelchairAlt: WheelchairAlt,
  WheelchairMove: WheelchairMove,
  WhiskeyGlass: WhiskeyGlass,
  Wifi: Wifi,
  Wifi3: Wifi3,
  WifiStrong: WifiStrong,
  WindWeather: Wind,
  WindowClose: WindowClose,
  WindowMaximize: WindowMaximize,
  WindowMinimize: WindowMinimize,
  WindowRestore: WindowRestore,
  WineBottleFood: WineBottle,
  WineGlassFood: WineGlass,
  WineGlassAlt: WineGlassAlt,
  WineGlassEmptyFood: WineGlassEmpty,
  Won: Won,
  WonSign: WonSign,
  WormAnimal: Worm,
  Wrench: Wrench,
  letterX: Xletter,
  XRay: XRay,
  Xmark: Xmark,
  XmarkCircle: XmarkCircle,
  XmarkSquare: XmarkSquare,
  XmarksLines: XmarksLines,
  letterY: Yletter,
  Yen: Yen,
  YenSign: YenSign,
  YinYang: YinYang,
  letterZ: Zletter,
  Zap: Zap,
};
