import {
  Ad,
  Add,
  AddressBook,
  AddressCard,
  Adjust,
  AirFreshener,
  AlignCenter2,
  AlignJustify2,
  AlignLeft2,
  AlignRight2,
  Allergies,
  Ambulance,
  AmericanSignLanguageInterpreting,
  Anchor2,
  AnchorCircleCheck,
  AnchorCircleExclamation,
  AnchorCircleXmark,
  AnchorLock,
  AngleDoubleDown,
  AngleDoubleLeft,
  AngleDoubleRight,
  AngleDoubleUp,
  AngleDown,
  AngleLeft,
  AngleRight,
  AnglesDown,
  AnglesLeft,
  AnglesRight,
  AnglesUp,
  AngleUp,
  Angry,
  Ankh,
  AppleAlt,
  AppleWhole,
  Archive2,
  Archway,
  AreaChart,
  ArrowAltCircleDown,
  ArrowAltCircleLeft,
  ArrowAltCircleRight,
  ArrowAltCircleUp,
  ArrowRightArrowLeft,
  ArrowRightFromBracket,
  ArrowRightFromFile,
  ArrowRightLong,
  ArrowRightRotate,
  ArrowRightToBracket,
  ArrowRightToCity,
  ArrowRightToFile,
  ArrowRotateBack,
  ArrowRotateBackward,
  ArrowRotateForward,
  ArrowRotateLeft,
  ArrowRotateRight,
  Arrows,
  ArrowsAlt,
  ArrowsAltH,
  ArrowsAltV,
  ArrowsDownToLine,
  ArrowsDownToPeople,
  ArrowsLeftRight,
  ArrowsRotate,
  ArrowsUpDown,
  ArrowTrendDown,
  ArrowTrendUp,
  ArrowTurnDown,
  ArrowTurnUp,
  ArrowUp19,
  ArrowUp91,
  ArrowUpAZ,
  ArrowUpFromBracket,
  ArrowUpFromGroundWater,
  ArrowUpFromWaterPump,
  ArrowUpLong,
  ArrowUpRightDots,
  ArrowUpRightFromSquare,
  ArrowUpShortWide,
  ArrowUpWideShort,
  ArrowUpZA,
  AslInterpreting,
  AssistiveListeningSystems,
  Asterisk,
  At,
  Atlas,
  Atom,
  AudioDescription,
  AustralSign,
  Automobile,
  Award2,
  Baby,
  BabyCarriage,
  Backspace,
  Backward,
  BackwardFast,
  BackwardStep,
  Bacon,
  Bacteria,
  Bacterium,
  BagShopping,
  Bahai,
  BahtSign,
  BalanceScale,
  BalanceScaleLeft,
  BalanceScaleRight,
  Ban,
  BandAid,
  BanSmoking,
  Bletter,
  Bookmark,
  BookMedical,
  BookOpen,
  BookOpenReader,
  BookQuran,
  BookReader,
  BookSkull,
  BookTanakh,
  BorderAll,
  BorderNone,
  BorderStyle,
  BorderTopLeft,
  BoreHole,
  BottleDroplet,
  BottleWater,
  BowlFood,
  BowlingBall,
  BowlRice,
  Box,
  BoxArchive,
  Boxes,
  BoxesPacking,
  BoxesStacked,
  BoxOpen,
  BoxTissue,
  Braille,
  Brain,
  BrazilianRealSign,
  BreadSlice,
  Bridge,
  BridgeCircleCheck,
  BridgeCircleExclamation,
  BridgeCircleXmark,
  BridgeLock,
  BridgeWater,
  Briefcase,
  BriefcaseClock,
  BriefcaseMedical,
  BroadcastTower,
  Broom,
  BroomBall,
  Brush,
  Bucket,
  Bug,
  Bugs,
  BugSlash,
  Building,
  BuildingCircleArrowRight,
  BuildingCircleCheck,
  BuildingCircleExclamation,
  BuildingCircleXmark,
  BuildingColumns,
  BuildingFlag,
  BuildingLock,
  BuildingNgo,
  BuildingShield,
  BuildingUn,
  BuildingUser,
  BuildingWheat,
  Bullhorn,
  Bullseye,
  Burger,
  Burn,
  Burst,
  Bus,
  BusAlt,
  BusinessTime,
  BusSimple,
  Cab,
  CableCar,
  Cake,
  CakeCandles,
  Calculator,
  Calendar,
  CalendarAlt,
  CalendarCheck,
  CalendarDay,
  CalendarDays,
  CalendarMinus,
  CalendarPlus,
  CalendarTimes,
  CalendarWeek,
  CalendarXmark,
  Camera,
  CameraAlt,
  CameraRetro,
  CameraRotate,
  Campground,
  Cancel,
  CandyCane,
  Cannabis,
  Capsules,
  Car,
  CarAlt,
  Caravan,
  CarBattery,
  CarBurst,
  CarCrash,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretSquareDown,
  CaretSquareLeft,
  CaretSquareRight,
  CaretSquareUp,
  CaretUp,
  CarOn,
  CarRear,
  CarriageBaby,
  Carrot,
  CarSide,
  CartArrowDown,
  CartFlatbed,
  CartFlatbedSuitcase,
  CartPlus,
  CartShopping,
  CarTunnel,
  CashRegister,
  Cat,
  CediSign,
  CentSign,
  Certificate,
  Chain,
  ChainBroken,
  ChainSlash,
  Chair,
  Chalkboard,
  ChalkboardTeacher,
  ChalkboardUser,
  ChampagneGlasses,
  ChargingStation,
  ChartArea,
  ChartBar,
  ChartColumn,
  ChartDiagram,
  ChartGantt,
  ChartLine,
  ChartPie,
  ChartSimple,
  Check,
  CheckCircle,
  CheckDouble,
  CheckSquare,
  CheckToSlot,
  Cheese,
  Chess,
  ChessBishop,
  ChessBoard,
  ChessKing,
  ChessKnight,
  ChessPawn,
  ChessQueen,
  ChessRook,
  ChevronCircleDown,
  ChevronCircleLeft,
  ChevronCircleRight,
  ChevronCircleUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Child,
  ChildCombatant,
  ChildDress,
  ChildReaching,
  Children,
  ChildRifle,
  Church,
  Circle,
  CircleArrowDown,
  CircleArrowLeft,
  CircleArrowRight,
  CircleArrowUp,
  CircleCheck,
  CircleChevronDown,
  CircleChevronLeft,
  CircleChevronRight,
  CircleChevronUp,
  CircleDollarToSlot,
  CircleDot,
  CircleDown,
  CircleExclamation,
  CircleH,
  CircleHalfStroke,
  CircleInfo,
  CircleLeft,
  CircleMinus,
  CircleNodes,
  CircleNotch,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleQuestion,
  CircleRadiation,
  CircleRight,
  CircleStop,
  CircleUp,
  CircleUser,
  CircleXmark,
  City,
  Clapperboard,
  ClinicMedical,
  Clipboard2,
  ClipboardCheck,
  ClipboardList,
  ClipboardQuestion,
  ClipboardUser,
  Clock,
  ClockFour,
  ClockRotateLeft,
  Clone,
  Close,
  ClosedCaptioning,
  Cloud,
  CloudArrowDown,
  CloudArrowUp,
  CloudBolt,
  CloudDownload,
  CloudDownloadAlt,
  CloudMeatball,
  CloudMoon,
  CloudMoonRain,
  CloudRain,
  CloudShowersHeavy,
  CloudShowersWater,
  CloudSun,
  CloudSunRain,
  CloudUpload,
  CloudUploadAlt,
  Clover,
  Cny,
  Cocktail,
  Code,
  CodeBranch,
  CodeCommit,
  CodeCompare,
  CodeFork,
  CodeMerge,
  CodePullRequest,
  Coffee2,
  Cog,
  Cogs,
  Coins,
  ColonSign,
  Columns,
  Comment2,
  CommentAlt,
  CommentDollar,
  CommentDots,
  Commenting,
  CommentMedical,
  CommentNodes,
  Comments,
  CommentsDollar,
  CommentSlash,
  CommentSms,
  CompactDisc,
  Compass2,
  CompassDrafting,
  Compress,
  CompressAlt,
  CompressArrowsAlt,
  Computer,
  ComputerMouse,
  ConciergeBell,
  ContactBook,
  ContactCard,
  Cookie,
  CookieBite,
} from "./FontAwesome";

// // // props
interface IconsProps {
  className?: string;
}

export const AwesomeIconsMap: Record<string, React.FC<IconsProps>> = {
  Ad: Ad,
  plus: Add,
  AddressBook: AddressBook,
  AddressCard: AddressCard,
  Adjust: Adjust,
  AirFreshener: AirFreshener,
  AlignCenter: AlignCenter2,
  AlignJustify: AlignJustify2,
  AlignLeft: AlignLeft2,
  AlignRight: AlignRight2,
  Allergies: Allergies,
  Ambulance: Ambulance,
  AmericanSignLanguageInterpreting: AmericanSignLanguageInterpreting,
  anchor: Anchor2,
  AnchorCircleCheck: AnchorCircleCheck,
  AnchorCircleExclamation: AnchorCircleExclamation,
  AnchorCircleXmark: AnchorCircleXmark,
  AnchorLock: AnchorLock,
  AngleDoubleDown: AngleDoubleDown,
  AngleDoubleLeft: AngleDoubleLeft,
  AngleDoubleRight: AngleDoubleRight,
  AngleDoubleUp: AngleDoubleUp,
  AngleDown: AngleDown,
  AngleLeft: AngleLeft,
  AngleRight: AngleRight,
  AngleUp: AngleUp,
  AnglesDown: AnglesDown,
  AnglesLeft: AnglesLeft,
  AnglesRight: AnglesRight,
  AnglesUp: AnglesUp,
  Angry: Angry,
  Ankh: Ankh,
  AppleAlt: AppleAlt,
  AppleWhole: AppleWhole,
  archive: Archive2,
  Archway: Archway,
  AreaChart: AreaChart,
  ArrowAltCircleDown: ArrowAltCircleDown,
  ArrowAltCircleLeft: ArrowAltCircleLeft,
  ArrowAltCircleRight: ArrowAltCircleRight,
  ArrowAltCircleUp: ArrowAltCircleUp,
  ArrowCircleDown: ArrowAltCircleDown,
  ArrowCircleLeft: ArrowAltCircleLeft,
  ArrowCircleRight: ArrowAltCircleRight,
  ArrowCircleUp: ArrowAltCircleUp,
  ArrowRightArrowLeft: ArrowRightArrowLeft,
  ArrowRightFromBracket: ArrowRightFromBracket,
  ArrowRightFromFile: ArrowRightFromFile,
  ArrowRightLong: ArrowRightLong,
  ArrowRightRotate: ArrowRightRotate,
  ArrowRightToBracket: ArrowRightToBracket,
  ArrowRightToCity: ArrowRightToCity,
  ArrowRightToFile: ArrowRightToFile,
  ArrowRotateBack: ArrowRotateBack,
  ArrowRotateBackward: ArrowRotateBackward,
  ArrowRotateForward: ArrowRotateForward,
  ArrowRotateLeft: ArrowRotateLeft,
  ArrowRotateRight: ArrowRotateRight,
  ArrowTrendDown: ArrowTrendDown,
  ArrowTrendUp: ArrowTrendUp,
  ArrowTurnDown: ArrowTurnDown,
  ArrowTurnUp: ArrowTurnUp,
  ArrowUp19: ArrowUp19,
  ArrowUp91: ArrowUp91,
  ArrowUpAZ: ArrowUpAZ,
  ArrowUpFromBracket: ArrowUpFromBracket,
  ArrowUpFromGroundWater: ArrowUpFromGroundWater,
  ArrowUpFromWaterPump: ArrowUpFromWaterPump,
  ArrowUpLong: ArrowUpLong,
  ArrowUpRightDots: ArrowUpRightDots,
  ArrowUpRightFromSquare: ArrowUpRightFromSquare,
  ArrowUpShortWide: ArrowUpShortWide,
  ArrowUpWideShort: ArrowUpWideShort,
  ArrowUpZA: ArrowUpZA,
  Arrows: Arrows,
  ArrowsAlt: ArrowsAlt,
  ArrowsAltH: ArrowsAltH,
  ArrowsAltV: ArrowsAltV,
  ArrowsDownToLine: ArrowsDownToLine,
  ArrowsDownToPeople: ArrowsDownToPeople,
  ArrowsLeftRight: ArrowsLeftRight,
  ArrowsRotate: ArrowsRotate,
  ArrowsUpDown: ArrowsUpDown,
  AslInterpreting: AslInterpreting,
  AssistiveListeningSystems: AssistiveListeningSystems,
  Asterisk: Asterisk,
  At: At,
  Atlas: Atlas,
  Atom: Atom,
  AudioDescription: AudioDescription,
  AustralSign: AustralSign,
  Automobile: Automobile,
  Award: Award2,
  B: Bletter,
  Baby: Baby,
  BabyCarriage: BabyCarriage,
  Backspace: Backspace,
  Backward: Backward,
  BackwardFast: BackwardFast,
  BackwardStep: BackwardStep,
  Bacon: Bacon,
  Bacteria: Bacteria,
  Bacterium: Bacterium,
  BagShopping: BagShopping,
  Bahai: Bahai,
  BahtSign: BahtSign,
  BalanceScale: BalanceScale,
  BalanceScaleLeft: BalanceScaleLeft,
  BalanceScaleRight: BalanceScaleRight,
  Ban: Ban,
  BanSmoking: BanSmoking,
  BandAid: BandAid,
  BookMedical: BookMedical,
  BookOpen: BookOpen,
  BookOpenReader: BookOpenReader,
  BookQuran: BookQuran,
  BookReader: BookReader,
  BookSkull: BookSkull,
  BookTanakh: BookTanakh,
  Bookmark: Bookmark,
  BorderAll: BorderAll,
  BorderNone: BorderNone,
  BorderStyle: BorderStyle,
  BorderTopLeft: BorderTopLeft,
  BoreHole: BoreHole,
  BottleDroplet: BottleDroplet,
  BottleWater: BottleWater,
  BowlFood: BowlFood,
  BowlRice: BowlRice,
  BowlingBall: BowlingBall,
  Box: Box,
  BoxArchive: BoxArchive,
  BoxOpen: BoxOpen,
  BoxTissue: BoxTissue,
  Boxes: Boxes,
  BoxesPacking: BoxesPacking,
  BoxesStacked: BoxesStacked,
  Braille: Braille,
  Brain: Brain,
  BrazilianRealSign: BrazilianRealSign,
  BreadSlice: BreadSlice,
  Bridge: Bridge,
  BridgeCircleCheck: BridgeCircleCheck,
  BridgeCircleExclamation: BridgeCircleExclamation,
  BridgeCircleXmark: BridgeCircleXmark,
  BridgeLock: BridgeLock,
  BridgeWater: BridgeWater,
  Briefcase: Briefcase,
  BriefcaseClock: BriefcaseClock,
  BriefcaseMedical: BriefcaseMedical,
  BroadcastTower: BroadcastTower,
  Broom: Broom,
  BroomBall: BroomBall,
  Brush: Brush,
  Bucket: Bucket,
  Bug: Bug,
  BugSlash: BugSlash,
  Bugs: Bugs,
  Building: Building,
  BuildingCircleArrowRight: BuildingCircleArrowRight,
  BuildingCircleCheck: BuildingCircleCheck,
  BuildingCircleExclamation: BuildingCircleExclamation,
  BuildingCircleXmark: BuildingCircleXmark,
  BuildingColumns: BuildingColumns,
  BuildingFlag: BuildingFlag,
  BuildingLock: BuildingLock,
  BuildingNgo: BuildingNgo,
  BuildingShield: BuildingShield,
  BuildingUn: BuildingUn,
  BuildingUser: BuildingUser,
  BuildingWheat: BuildingWheat,
  Bullhorn: Bullhorn,
  Bullseye: Bullseye,
  Burger: Burger,
  Burn: Burn,
  Burst: Burst,
  Bus: Bus,
  BusAlt: BusAlt,
  BusSimple: BusSimple,
  BusinessTime: BusinessTime,
  Cab: Cab,
  CableCar: CableCar,
  Cake: Cake,
  CakeCandles: CakeCandles,
  Calculator: Calculator,
  Calendar: Calendar,
  CalendarAlt: CalendarAlt,
  CalendarCheck: CalendarCheck,
  CalendarDay: CalendarDay,
  CalendarDays: CalendarDays,
  CalendarMinus: CalendarMinus,
  CalendarPlus: CalendarPlus,
  CalendarTimes: CalendarTimes,
  CalendarWeek: CalendarWeek,
  CalendarXmark: CalendarXmark,
  Camera: Camera,
  CameraAlt: CameraAlt,
  CameraRetro: CameraRetro,
  CameraRotate: CameraRotate,
  Campground: Campground,
  Cancel: Cancel,
  CandyCane: CandyCane,
  Cannabis: Cannabis,
  Capsules: Capsules,
  Car: Car,
  CarAlt: CarAlt,
  CarBattery: CarBattery,
  CarBurst: CarBurst,
  CarCrash: CarCrash,
  CarOn: CarOn,
  CarRear: CarRear,
  CarSide: CarSide,
  CarTunnel: CarTunnel,
  Caravan: Caravan,
  CaretDown: CaretDown,
  CaretLeft: CaretLeft,
  CaretRight: CaretRight,
  CaretSquareDown: CaretSquareDown,
  CaretSquareLeft: CaretSquareLeft,
  CaretSquareRight: CaretSquareRight,
  CaretSquareUp: CaretSquareUp,
  CaretUp: CaretUp,
  CarriageBaby: CarriageBaby,
  Carrot: Carrot,
  CartArrowDown: CartArrowDown,
  CartFlatbed: CartFlatbed,
  CartFlatbedSuitcase: CartFlatbedSuitcase,
  CartPlus: CartPlus,
  CartShopping: CartShopping,
  CashRegister: CashRegister,
  Cat: Cat,
  CediSign: CediSign,
  CentSign: CentSign,
  Certificate: Certificate,
  Chain: Chain,
  ChainBroken: ChainBroken,
  ChainSlash: ChainSlash,
  Chair: Chair,
  Chalkboard: Chalkboard,
  ChalkboardTeacher: ChalkboardTeacher,
  ChalkboardUser: ChalkboardUser,
  ChampagneGlasses: ChampagneGlasses,
  ChargingStation: ChargingStation,
  ChartArea: ChartArea,
  ChartBar: ChartBar,
  ChartColumn: ChartColumn,
  ChartDiagram: ChartDiagram,
  ChartGantt: ChartGantt,
  ChartLine: ChartLine,
  ChartPie: ChartPie,
  ChartSimple: ChartSimple,
  Check: Check,
  CheckCircle: CheckCircle,
  CheckDouble: CheckDouble,
  CheckSquare: CheckSquare,
  CheckToSlot: CheckToSlot,
  Cheese: Cheese,
  Chess: Chess,
  ChessBishop: ChessBishop,
  ChessBoard: ChessBoard,
  ChessKing: ChessKing,
  ChessKnight: ChessKnight,
  ChessPawn: ChessPawn,
  ChessQueen: ChessQueen,
  ChessRook: ChessRook,
  ChevronCircleDown: ChevronCircleDown,
  ChevronCircleLeft: ChevronCircleLeft,
  ChevronCircleRight: ChevronCircleRight,
  ChevronCircleUp: ChevronCircleUp,
  ChevronDown: ChevronDown,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  ChevronUp: ChevronUp,
  Child: Child,
  ChildCombatant: ChildCombatant,
  ChildDress: ChildDress,
  ChildReaching: ChildReaching,
  ChildRifle: ChildRifle,
  Children: Children,
  Church: Church,
  Circle: Circle,
  CircleArrowDown: CircleArrowDown,
  CircleArrowLeft: CircleArrowLeft,
  CircleArrowRight: CircleArrowRight,
  CircleArrowUp: CircleArrowUp,
  CircleCheck: CircleCheck,
  CircleChevronDown: CircleChevronDown,
  CircleChevronLeft: CircleChevronLeft,
  CircleChevronRight: CircleChevronRight,
  CircleChevronUp: CircleChevronUp,
  CircleDollarToSlot: CircleDollarToSlot,
  CircleDot: CircleDot,
  CircleDown: CircleDown,
  CircleExclamation: CircleExclamation,
  CircleH: CircleH,
  CircleHalfStroke: CircleHalfStroke,
  CircleInfo: CircleInfo,
  CircleLeft: CircleLeft,
  CircleMinus: CircleMinus,
  CircleNodes: CircleNodes,
  CircleNotch: CircleNotch,
  CirclePause: CirclePause,
  CirclePlay: CirclePlay,
  CirclePlus: CirclePlus,
  CircleQuestion: CircleQuestion,
  CircleRadiation: CircleRadiation,
  CircleRight: CircleRight,
  CircleStop: CircleStop,
  CircleUp: CircleUp,
  CircleUser: CircleUser,
  CircleXmark: CircleXmark,
  City: City,
  Clapperboard: Clapperboard,
  ClinicMedical: ClinicMedical,
  Clipboard: Clipboard2,
  ClipboardCheck: ClipboardCheck,
  ClipboardList: ClipboardList,
  ClipboardQuestion: ClipboardQuestion,
  ClipboardUser: ClipboardUser,
  Clock: Clock,
  ClockFour: ClockFour,
  ClockRotateLeft: ClockRotateLeft,
  Clone: Clone,
  Close: Close,
  ClosedCaptioning: ClosedCaptioning,
  Cloud: Cloud,
  CloudArrowDown: CloudArrowDown,
  CloudArrowUp: CloudArrowUp,
  CloudBolt: CloudBolt,
  CloudDownload: CloudDownload,
  CloudDownloadAlt: CloudDownloadAlt,
  CloudMeatball: CloudMeatball,
  CloudMoon: CloudMoon,
  CloudMoonRain: CloudMoonRain,
  CloudRain: CloudRain,
  CloudShowersHeavy: CloudShowersHeavy,
  CloudShowersWater: CloudShowersWater,
  CloudSun: CloudSun,
  CloudSunRain: CloudSunRain,
  CloudUpload: CloudUpload,
  CloudUploadAlt: CloudUploadAlt,
  Clover: Clover,
  Cny: Cny,
  Cocktail: Cocktail,
  Code: Code,
  CodeBranch: CodeBranch,
  CodeCommit: CodeCommit,
  CodeCompare: CodeCompare,
  CodeFork: CodeFork,
  CodeMerge: CodeMerge,
  CodePullRequest: CodePullRequest,
  Coffee: Coffee2,
  Cog: Cog,
  Cogs: Cogs,
  Coins: Coins,
  ColonSign: ColonSign,
  Columns: Columns,
  Comment: Comment2,
  CommentAlt: CommentAlt,
  CommentDollar: CommentDollar,
  CommentDots: CommentDots,
  CommentMedical: CommentMedical,
  CommentNodes: CommentNodes,
  CommentSlash: CommentSlash,
  CommentSms: CommentSms,
  Commenting: Commenting,
  Comments: Comments,
  CommentsDollar: CommentsDollar,
  CompactDisc: CompactDisc,
  Compass: Compass2,
  CompassDrafting: CompassDrafting,
  Compress: Compress,
  CompressAlt: CompressAlt,
  CompressArrowsAlt: CompressArrowsAlt,
  Computer: Computer,
  ComputerMouse: ComputerMouse,
  ConciergeBell: ConciergeBell,
  ContactBook: ContactBook,
  ContactCard: ContactCard,
  Cookie: Cookie,
  CookieBite: CookieBite,
};
